### ISSUE TITLE
Unable to mock results with datetime columns

### ISSUE THREAD

**Issue by Hebo** [DATA-DOG/go-sqlmock#1]
Hey,

How can I mock columns that are stored as datetimes? It seems that `RowsFromCSVString` sets `driver.Value`s that are always `[]byte`, and `Scan` is unable to parse `time.time` objects from them:

```
Scan error on column index 4: unsupported driver -> Scan pair: []uint8 -> *time.Time
```

I'd guess this would work if either `RowsFromCSVString` was able to directly create `time.time` objects when it encounters them or there was another way to assemble `sqlmock.rows` objects.

Example:

```
sqlmock.ExpectQuery("SELECT now()").
    WillReturnRows(sqlmock.RowsFromCSVString([]string{"now"}, "2014-02-12 16:04:15.879588-08"))

# sql: Scan error on column index 0: unsupported driver -> Scan pair: []uint8 -> *time.Time
```

**Comment by rvmishra** [comment]
Hey!

Is this issue not resolved? I do not see RowFromInterface in [rows.go](https://github.com/DATA-DOG/go-sqlmock/blob/master/rows.go)

I am facing this problem when mocking mysql.
