### ISSUE TITLE
How can I generate Expect for 'replace'

### ISSUE THREAD

**Issue by kof02guy** [DATA-DOG/go-sqlmock#100]
Hi, team,
In my code, I'll execute sql like:
```
conn, err := sql.Open("mysql", cfConn)
conn.Query("replace audience_network_stats(process_date, network_id, data_provider_id, is_matched, visitor_count, data_provider_visitor_count, matched_data_provider_visitor_count) values('2017-11-21', 0, 381110, 1, 15421696, 715481088, 0);")
```

how can I write the expect using sqlmock?
I tried 
`sqlMock.ExpectQuery("replace audience_network_stats").WithArgs('2017-11-21', 0, 381110, 1, 15421696, 715481088, 0).WillReturnError(nil)`
But I've got an error saying that this is not met

**Comment by kof02guy** [comment]
Hi @l3pp4rd 
Yes, we used conn.Query instead of conn.Exec.

**Comment by kof02guy** [comment]
Hi, @l3pp4rd 
Why is this issue closed?

**Comment by l3pp4rd** [comment]
`Yes, we used conn.Query instead of conn.Exec.` was it the problem or not? If not then reopen, but let me see the mock code and the actual db usage code for that query if the issue still remains

**Comment by l3pp4rd** [comment]
if you expect query `sqlMock.ExpectQuery("replace audience_network_stats").WithArgs('2017-11-21', 0, 381110, 1, 15421696, 715481088, 0).WillReturnError(nil)` then it must return rows. If you do not return rows but result instead, then use conn.Exec

**Comment by kof02guy** [comment]
Thanks @l3pp4rd .The problem was solved. I should use ? instead of formatting string to specify the arguments in my code.

**Comment by l3pp4rd** [comment]
argument placeholders should be used based on your sql driver support, the regexp used in mock to match the query should be escaped properly, but it all boils down just to regex matching if that is what you mean by **?**.
