### ISSUE TITLE
Named Args with sqlx

### ISSUE THREAD

**Issue by bhechinger** [DATA-DOG/go-sqlmock#103]
I'm using sqlx's Named Args via:

```
stmt, err := db.Conn.PrepareNamed("select * from shows where active = :active")
s := Shows{Active: true}
stmt.Select(&shows, s)
```

I'm not sure how to do this with sqlmock. `sql.Named()` and `sqlx.Named()` are totally different things.

**Comment by l3pp4rd** [comment]
Hi, I do not use any libraries on top of standard sql, maybe someone from community could answer that on reddit or stackoverflow.

**Comment by bhechinger** [comment]
So digging into this it looks like the general consensus is if you want named parameters you need to use sqlx.

Oh well. :)
