### ISSUE TITLE
WillReturnRows only returning partial (2 out of 5) columns

### ISSUE THREAD

**Issue by sevagh** [DATA-DOG/go-sqlmock#104]
Hello,

My code looks something like this:

```go
fmt.Println(dbRows)
//&{[channel name pd_integration_key pd_service_name pd_escalation_policy] [[test_channel_1 test_name_1 123456 oncallbot_unit_test_1 oncallbot_unit_test_policy_1] [test_channel_2 test_name abcdefg oncallbot_unit_test_2 oncallbot_unit_test_policy_2]] 0 map[] <nil>}

mock.ExpectQuery("SELECT (.+) FROM \"escalations\"").WillReturnRows(dbRows)

var escalations []Escalation
actualRows := db.Raw("SELECT * FROM \"escalations\"", &escalations)

fmt.Println(actualRows)
//[{test_channel_1 test_name_1   } {test_channel_2 test_name   }]
```

Am I doing something wrong here? When using a local instance of Postgresql in Docker, the code `db.Raw("SELECT * FROM \"escalations\"", &escalations)` returns full data.

**Comment by l3pp4rd** [comment]
Hi, do you create rows using `sqlmock.NewRows(columns)` ? if yes, could you create a tiny test case, since that should work properly, there are many test cases in the library

**Comment by sevagh** [comment]
Yes. I believe this is a possible bad interaction with the `gorm` library. I found a different way to test it for now, thanks.
