### ISSUE TITLE
Query not matching when using dot notation

### ISSUE THREAD

**Issue by gprivitera** [DATA-DOG/go-sqlmock#107]
Hello, I'm trying to test-mock a function that uses a very long query (didn't post all of it):
```
query := `SELECT
XX.TransT_lgnNumber AS transT_lgnNumber,
XX.TransT_intSequence AS transT_intSequence
... (bunch of more parameters)

FROM
tblTrans_Ticket XX
LEFT JOIN tblSession S WITH (NOLOCK)
ON XX.Session_lngSessionId = S.Session_lngSessionId
... (bunch of more left joins)

WHERE
(XX.TransT_dtmDateTime) < CONVERT(DATETIME,$1,121)
AND (XX.TransT_dtmDateTime) >= DATEADD(MINUTE,-$2,CONVERT(DATETIME,$1,121))

ORDER BY
XX.TransT_dtmRealTransTime`
```

No matter what I do the query is never matching when I run:

```
...
mock.ExpectPrepare(query)
mock.ExpectQuery(query).WithArgs("2017-01-01 00:00:00.000", "5")
...
```

I've checked the outcome of the test and what it says is:
```
2018/02/13 16:49:26 Prepare query string '...', does not match regex [...]
```
(where ... is my query in both occurrences, with no differences)

While debugging (here: https://github.com/DATA-DOG/go-sqlmock/blob/master/sqlmock.go#L356) I noticed that the `prefix` field in `regexpRO` variable seems to be tricked by the `.`s in the query
```
regexpRO: regexp.regexpRO
  prefix:  "SELECT TT"
```

In fact if I change my query removing my first dot, it becomes:
```
regexpRO: regexp.regexpRO
  prefix:  "SELECT TTTransT_lgnNumber AS transT_lgnNumber, TT
```

Am I doing something awfully wrong? Is the dot notation not supported?
Thanks, great tool so far!

**Comment by l3pp4rd** [comment]
hi, the query string must be escaped properly since it is a regular expression string. the reason why it is a regexp, is that you can make it shorter and much only unique parts of it where you can identify the query on methods being tested

**Comment by gprivitera** [comment]
Right, so I was doing something awfully wrong. 
Thanks for the prompt reply.
