### ISSUE TITLE
Errors are not delayed.

### ISSUE THREAD

**Issue by markuswrnp** [DATA-DOG/go-sqlmock#108]
If I apply both WillDelayFor() and WillReturnError() to an ExpectedExec, the error is returned right away, there is no delay.  What I expect is that the call to Exec() will delay for the requested time, then return the error.

**Comment by l3pp4rd** [comment]
Hi, yes that makes sense, are you willing to make a pull request?

**Comment by markuswrnp** [comment]
ok, I can make a pull request.

**Comment by markuswrnp** [comment]
@l3pp4rd  I'm getting an Authentication error when I try to push my branch.

**Comment by markuswrnp** [comment]
https://github.com/DATA-DOG/go-sqlmock/pull/110
