### ISSUE TITLE
Help: Query not expected while creating a Table

### ISSUE THREAD

**Issue by KarthikNayak** [DATA-DOG/go-sqlmock#109]
Hello,

I'm trying to mock a **_Automigration_** done using **_gorm_** which basically creates/modifies a table. Code I'm trying to mock and test is as follows.

`db := DB.AutoMigrate(<struct here>)` 

(DB is initialised to a new DB connection via gorm)

Trying to test this by mocking the SQL expected as follows: 

`mock.ExpectQuery("CREATE TABLE .*")`

Which gives me the following error: 

2018/02/19 14:28:05 Error while performing migrations: call to ExecQuery 'CREATE TABLE `flags` (`id` int unsigned AUTO_INCREMENT,`created_at` timestamp NULL,`updated_at` timestamp NULL,`deleted_at` timestamp NULL,`name` varchar(255) NOT NULL UNIQUE,`enabled` varchar(255) NOT NULL , PRIMARY KEY (`id`))' with args [] was not expected

How do I go about this?

**Comment by l3pp4rd** [comment]
Hi `mock.ExpectQuery("CREATE TABLE .*")` will match only one create table query, if you have more, the expectations have to be repeated as many times as you create tables.

**Comment by KarthikNayak** [comment]
@l3pp4rd Thanks! Seems that the problem was I was using `ExpectQuery` whereas I needed to be using `ExpectExec`. Closing!

**Comment by l3pp4rd** [comment]
ah right, did not notice this

**Comment by AdelBouridah** [comment]
Hi @KarthikNayak  please i face the same problem with automigration (gormV2) and testing mock. I have used ExectExec but I have always the same error as you mentione above. Any hints please. Hereafter the error:

"ExecQuery: could not match actual sql: \"CREATE TABLE \"line\" (\"id\" text,\"name\" text,\"is_active\" boolean,\"start_station\" text DEFAULT null,\"end_station\" text DEFAULT null,PRIMARY KEY (\"id\"))\" with expected regexp \"CREATE TABLE \"line\" (\"id\" text,\"name\" text,\"is_active\" boolean,\"start_station\" text DEFAULT null,\"end_station\" text DEFAULT null,PRIMARY KEY (\"id\"))\""
