### ISSUE TITLE
Unable to use ExpectClose andExpectQuery in same test

### ISSUE THREAD

**Issue by peczenyj** [DATA-DOG/go-sqlmock#113]
I have a test where I want to test the return of `db.Close()`

I have this kind of code:
```go
instance, err := package.Constructor( db, ... )
...
err = instance.Close()
// assertions on err
```

the constructor check if db is valid by perform a particular query (I am reading a sqlite database, and in some cases if the file does not exists, the driver creates an empty database - so I need verify the schema). my solution was a test with two expectations: a Query with SELECT ... + Close() and this does not work.

I wrote a minimal test to reproduce the issue:

```go
func TestCloseWithOtherExpectations(t *testing.T) {
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
	}
	// defer db.Close()

	mock.ExpectQuery(`SELECT .*`).WillReturnRows()
	mock.ExpectClose().WillReturnError(fmt.Errorf(`ops`))

	_, err = db.Query("SELECT * FROM TABLE LIMIT 1")
	if err != nil {
		t.Errorf("should not return error on db.Query")
	}

	err = db.Close()
	if err == nil {
		t.Errorf("expected any error from db.Close()")
	} else if err.Error() != `ops` {
		t.Errorf("expected 'ops' error from db.Close()")
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("there were unfulfilled expectations: %s", err)
	}
}
```

output:
```
--- FAIL: TestCloseWithOtherExpectations (0.00s)
	sqlmock_test.go:27: expected any error from db.Close()
	sqlmock_test.go:32: there were unfulfilled expectations: there is a remaining expectation which was not matched: ExpectedClose => expecting database Close, which should return error: ops
```
I try set `mock.MatchExpectationsInOrder(false)` with no effect

what I expect:
* both assertion works
* some warning in the documentation if it is not allowed

The test works if I only assert the Close *OR* the Query ( comment the part of the code )

go version: 1.9 linux/amd64
version: I update my vendor today with latest `gopkg.in/DATA-DOG/go-sqlmock.v1`

**Comment by l3pp4rd** [comment]
I think golang db implementation never calls sql.driver.Close (which sqlmock expects to be called). the reason might be that there are no open connections. try calling db.Ping() after initialization of sqlmock, I think Query method never opens connection since you do not call any Next() on rows. that is my guess. interesting why [test for close](https://github.com/DATA-DOG/go-sqlmock/blob/master/sqlmock_test.go#L994) passes in all go versions.

**Comment by peczenyj** [comment]
Hello

I will try. If I comment all related to Query, the Close works fine.

**Comment by peczenyj** [comment]
Hello

the  `sqlmock.New()` already perform one `db.Ping()` 

```go
func (c *sqlmock) open() (*sql.DB, Sqlmock, error) {
	db, err := sql.Open("sqlmock", c.dsn)
	if err != nil {
		return db, c, err
	}
	return db, c, db.Ping() // <----
}
```

But I find the issue: since I was interested in perform one query and detect errors on the schema, I was ignoring all returned by `db.Query` except the error. Since I was not closing the rows the go `database/sql` was keeping one active connection and the `db.Close()` was not handle properly with the expectation.

by changing:

```
func TestCloseWithOtherExpectations(t *testing.T) {
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
	}
	// defer db.Close()
        // full query expectation with query and return
	mock.ExpectQuery(`SELECT .*`).WillReturnRows(sqlmock.NewRows([]string{"id"}).AddRow(1))
	mock.ExpectClose().WillReturnError(fmt.Errorf(`ops`))

	rows, err := db.Query("SELECT * FROM TABLE LIMIT 1")
	if err != nil {
		t.Errorf("should not return error on db.Query")
	}
	rows.Close() // explicit rows Close !

	err = db.Close()
	if err == nil {
		t.Errorf("expected any error from db.Close()")
	} else if err.Error() != `ops` {
		t.Errorf("expected 'ops' error from db.Close()")
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("there were unfulfilled expectations: %s", err)
	}
}
```

everything works fine. but to discover this I start to compare diffs of `spew.Dump` until realize there is something weird. I forge to check for `db.Stats()` too :)

Thanks

**Comment by l3pp4rd** [comment]
Cheers ;)
