### ISSUE TITLE
How to allow to pass string slice?

### ISSUE THREAD

**Issue by zloy531** [DATA-DOG/go-sqlmock#115]
`Error:      	Received unexpected error:
	            	sql: converting argument $2 type: unsupported type []string, a slice of string
	            	error with handling the line`

I'm using pgx and it correctly transforms the []string variable to appropriate type for PostgreSQL, but in tests with sqlmock, I see this error.

Example:
```
func TestShouldUpdateStats(t *testing.T) {
	db, _, err := sqlmock.New()
	if err != nil {
		t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
	}
	defer db.Close()
	products := []string{"hello", "world"}
	if _, err = db.Exec("INSERT INTO product_viewers (products) VALUES (?)", products); err != nil {
		log.Panic(err)
	}
}
```

How to allow to pass string slices? I can't find the way to register additional type myself.

**Comment by l3pp4rd** [comment]
Hi, you need to expect exec, with an argument of string slice, in order to match that argument implement the sqlmock.Argument interface

**Comment by zloy531** [comment]
Are you sure? The error seems to be from the internals of the sql package.

Also I've tried:
m.ExpectExec("INSERT INTO product_viewers (products) VALUES (?)").WithArgs([]string{"hello", "world"})
m.ExpectExec("INSERT INTO product_viewers (products) VALUES (?)").WithArgs(mock.Anything)

The same error.

**Comment by l3pp4rd** [comment]
well that simply means, that you are using **pgx** through it's own interface where it maps types into binary format internal to postgresql. go sql/driver does not support such features and sqlmock is only compatible with the standard library interface. I see **pgx** supports the sql/driver but without the features you are using.

**Comment by zloy531** [comment]
Thank you for the feedback.
Could you help me?
I think, that there isn't the reason to add this to sqlmock, because, it'll break compatibility with sql/driver.
But maybe you could help me and suggest, where could I find the functionality that responds to internal type conversions?
In any case, thank you for the help. I'll try to patch this locally.

**Comment by l3pp4rd** [comment]
well, I do not have time for it, at least not within next two weeks

**Comment by FlacoJones** [comment]
I was using sqlc generated methods which call `pq.Array` on all slices before passing them to the go sql exec command. try this:

you can try this in your tests

```
			// Define expected SQL statement
			// go-sqlmock CANNOT accept slices as arguments. Must convert to pq.Array first as is done in databse.BulkInsertCommits
			mock.ExpectExec("^-- name: BulkInsertCommits :exec.*").WithArgs(
				pq.Array(commitHash),
				pq.Array(author),
				pq.Array(authorEmail),
				pq.Array(authorDate),
				pq.Array(committerDate),
				pq.Array(message),
				pq.Array(insertions),
				pq.Array(deletions),
				pq.Array(filesChanged),
				pq.Array(repoUrls),
			).WillReturnResult(sqlmock.NewResult(1, 1))
```

Note as well that when doing this you will want `len(myArray) == cap(myArray)` - AKA just use fixed-size arrays

`pq.Array` will turn the empty slots in your dynamically-sized array into empty values which it then attempts to insert into the database, often causing "duplicate entry" errors
