### ISSUE TITLE
INSERT while mocking gorm

### ISSUE THREAD

**Issue by tfmertz** [DATA-DOG/go-sqlmock#118]
I'm having a lot of trouble mocking gorm INSERT queries. I was able to get my tests passing when selecting fine, but I am running into this error when inserting.

```
# Gorm's debug output
INSERT INTO "groups" ("created_at","updated_at","deleted_at","name","description") VALUES ('2018-05-01 17:46:15','2018-05-01 17:46:15',NULL,'Group 1','A good group') RETURNING "groups"."id"

# Error returned from *gorm.DB.Create
2018/05/01 17:46:15 Error creating group: call to Query 'INSERT INTO "groups" ("created_at","updated_at","deleted_at","name","description") VALUES ($1,$2,$3,$4,$5) RETURNING "groups"."id"' with args [{Name: Ordinal:1 Value:2018-05-01 17:46:15.384319544 -0700 PDT m=+0.005382104} {Name: Ordinal:2 Value:2018-05-01 17:46:15.384319544 -0700 PDT m=+0.005382104} {Name: Ordinal:3 Value:<nil>} {Name: Ordinal:4 Value:Group 1} {Name: Ordinal:5 Value:A good group}], was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
  - matches sql: '^INSERT INTO "groups" (.+)$'
  - is with arguments:
    0 - {}
    1 - {}
    2 - <nil>
    3 - Group 1
    4 - A good group
  - should return Result having:
      LastInsertId: 1
      RowsAffected: 1
```
I have tried multiple different versions of the regex, even tested the match using golang on regex101.com, but I can't seem to get my sqlmock to match gorm's insert.

Here is my test:
```
type AnyTime struct{} // I don't actually know if I even need this

func (a AnyTime) Match(v driver.Value) bool {
	_, ok := v.(time.Time)
	return ok
}

func TestGroupService_Create(t *testing.T) {
	db, mock, err := sqlmock.New()
	if err != nil {
		log.Fatalf("can't create sqlmock: %s", err)
	}
	models.DB, err = gorm.Open("postgres", db)
	if err != nil {
		log.Fatalf("can't open gorm connection: %s", err)
	}
	defer db.Close()

	models.DB.LogMode(true)

	name := "Group 1"
	description := "A good group"

	mock.ExpectExec("^INSERT INTO \"groups\" (.+)$").WithArgs(AnyTime{}, AnyTime{}, nil, name, description).WillReturnResult(sqlmock.NewResult(1, 1))

	s := GroupService{}

	req := &pb.CreateGroupRequest{
		Name: name,
		Description: description,
	}

	resp, err := s.Create(context.Background(), req)
	assert.Nil(t, err)

	if assert.NotNil(t, resp) {
		assert.Equal(t, resp.Group.Name, name)
		assert.Equal(t, resp.Group.Description, description)
	}

	err = mock.ExpectationsWereMet()
	assert.Nil(t, err)
}
```

and my service method I'm trying to test:
```
func (server *GroupService) Create(ctx context.Context, request *pb.CreateGroupRequest) (*pb.CreateGroupReply, error) {
	var group models.Group

	group.Name = request.Name
	group.Description = request.Description

	db := models.DB

	if err := db.Create(&group).Error; err != nil {
		log.Printf("Error creating group: %v", err)
		return nil, err
	}

	createReply := pb.CreateGroupReply{
		Group: mapGroupToService(group),
	}

	return &createReply, nil
}
```

I just can't seem to figure this out. Thanks!

**Comment by l3pp4rd** [comment]
Make sure you are not mixing the ExpectExec with ExpectQuery. You copied the wrong method used. Test calls `GroupService.Create` not `GroupService.Search`

**Comment by tfmertz** [comment]
Thanks for your help! I edited with the correct service method. I have got the `GroupService.Search` method to run and pass using `ExpectQuery("^SELECT (.+) FROM \"groups\" (.+)$")` Somehow the INSERT just isn't matching the gorm insert.

**Comment by tfmertz** [comment]
I was able to get the INSERT working by switching to the [go-mocket](https://github.com/Selvatico/go-mocket) library. It seems to be a GORM specific mocking lib. Thanks for taking a look!

The test now is:
```
func SetupTests() *gorm.DB {
	mocket.Catcher.Register()

	db, err := gorm.Open(mocket.DRIVER_NAME, "")
	if err != nil {
		log.Fatalf("error mocking gorm: %s", err)
	}
	// Log mode shows the query gorm uses, so we can replicate and mock it
	db.LogMode(true)
	models.DB = db

	return db
}

func TestGroupService_Create(t *testing.T) {
	db := SetupTests()
	defer db.Close()

	var mockedId int64 = 64
	mocket.Catcher.Reset().NewMock().WithQuery("INSERT INTO \"groups\"").WithId(mockedId)

	s := GroupService{}

	name := "Group 1"
	description := "A good group"

	req := &pb.CreateGroupRequest{
		Name: name,
		Description: description,
	}

	resp, err := s.Create(context.Background(), req)
	assert.Nil(t, err)

	if assert.NotNil(t, resp) {
		assert.Equal(t, uint32(mockedId), resp.Group.Id)
		assert.Equal(t, name, resp.Group.Name)
		assert.Equal(t, description, resp.Group.Description)
	}
}
```

**Comment by niponchi** [comment]
Got this issue too.

For some reason, `gorm` uses `QueryRow` instead of `Exec` for `INSERT` statement. `sqlmock` expect `INSERT` statement to be called with `Exec`, so it cannot catch the call.

https://github.com/jinzhu/gorm/blame/master/callback_create.go#L132

**Comment by wuxiaoxiaoshen** [comment]
gorm uses QueryRow instead of Exec for INSERT statement. sqlmock expect INSERT statement to be called with Exec, so it cannot catch the call.
so, what should i do when i use postgres with gorm?

**Comment by wuxiaoxiaoshen** [comment]
> Got this issue too.
> 
> For some reason, `gorm` uses `QueryRow` instead of `Exec` for `INSERT` statement. `sqlmock` expect `INSERT` statement to be called with `Exec`, so it cannot catch the call.
> 
> https://github.com/jinzhu/gorm/blame/master/callback_create.go#L132
> 
> **Edit**:
> This happen when I used `postgres` dialect. My workaround is to use `sqlite3`.
> 
> ```
> gorm.Open("sqlite3", db)
> ```
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)

wow, it is a perfect method to solve question when use postgres and gorm.

**Comment by davincilchen** [comment]
Hi tfmertz,
    Can you show your code s.Create in TestGroupService_Create ?
   Return failed when  I call TestGroupService_Create.

**Comment by shadracktaeli** [comment]
@l3pp4rd having the same issue with `INSERT` is there a work around other than switching to `go-mocket`?

**Comment by Gidraff** [comment]
Why is it so painful to mock insert queries?

**Comment by JokerQyou** [comment]
Gorm does not use `Exec` because PostgreSQL can do `RETURNING` in a single `INSERT` statement, but to be able to fetch this returning value `QueryRow` is required rather than `Exec`. I guess by leveraging this feature, gorm does not need to do any other operation to obtain primary key of the item it just inserted.

To mock an insert query you can do this:

```go
mock.ExpectQuery(`INSERT INTO "table" (.+) RETURNING`).
	WithArgs(sqlmock.AnyArg(), value1, value2).
	WillReturnRows(sqlmock.NewRows([]string{"id"}).AddRow(1))
```

The tricky part is: to use `WithArgs` you must know the exact number of arguments, and replace those you have no control over (like `CreatedAt`, which is managed automatically by gorm) with `sqlmock.AnyArg()`. If you'd like to also match for argument ordinals, well, there is still more hard work...

**Comment by l3pp4rd** [comment]
sqlmock will not attempt to make abstractions specifically for frameworks such as gorm or any other. if they use complicated abstractions, use then [txdb](https://github.com/DATA-DOG/go-txdb) for faster functional tests instead of unit tests, I personally never use any frameworks for these or similar reasons

**Comment by RajivBobble** [comment]
Why is this happening???
My Query is 
`mock.ExpectQuery("INSERT INTO user.*").WithArgs(sqlmock.AnyArg(), 1, 1).WillReturnRows(rowID)
`


And Got this Error:
```
call to database transaction Begin, was not
 expected, next expectation is: ExpectedQuery => expecting Query, QueryContext or 
QueryRow which:
  - matches sql: 'INSERT INTO user.*'
  - is with arguments:
    0 - {}
    1 - 1
    2 - 1
  - should return rows:
    row 0 - [1]
```
And If using 
`	mock.ExpectExec("INSERT INTO user.*").WillReturnResult(sqlmock.NewResult(1, 1))
`
Getting this error:
`all expectations were already fulfilled, call to database transaction Begin was not expected`

**Comment by rxantony** [comment]
you must update your gorm version into github.com/jinzhu/gorm v1.9.2

> all expectations were already fulfilled, call to database transaction Begin was not expected

**Comment by sauraz** [comment]
> you must update your gorm version into github.com/jinzhu/gorm v1.9.2
> 
> > all expectations were already fulfilled, call to database transaction Begin was not expected

Worked perfectly. Thanks!

**Comment by kkrime** [comment]
Hi guys,

I've encountered the same problem and going through this issue I can see that it was closed by @tfmertz - his solution was switching to [go-mocket ](https://github.com/Selvatico/go-mocket) - which isn't really a solution.

This is a still on going issue with gorm/postgres, would it be possible for this issue to be reopened and for  someone to look into this?

Thanks

**Comment by fenriz07** [comment]
I have same problem.

**Comment by rossnelson** [comment]
I've landed on this issue a few times while working with sqlmock and gorm. 

I have a slightly different scenario and it took me a bit to understand what was happening. I had a struct that I defined the `ID` column as a string and it was using `ExecQuery` when calling `Create(&model)`. My mocks were functional using `ExpectExec`. When I switched to an `int` my mock stopped functioning. Once I realized gorm switched to using `Query` when I changed the data type I was able to get tests passing again using `ExpectQuery` instead.

Consider these errors showing the behavior:

When ID column is defined as an `int` and using `ExpectExec`:

```
call to Query 'INSERT INTO "ingestable_contracts" ("file_name","merchant_id","merchant","account_number","order_number","jdata","status","step_name","meta","errors","created_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING "id"' with args [{Name: Ordinal:1 Value:manual_occurrence} {Name: Ordinal:2 Value:} {Name: Ordinal:3 Value:ashret} {Name: Ordinal:4 Value:} {Name: Ordinal:5 Value:} {Name: Ordinal:6 Value:null} {Name: Ordinal:7 Value:Processing} {Name: Ordinal:8 Value:expand_ingestable} {Name: Ordinal:9 Value:null} {Name: Ordinal:10 Value:null} {Name: Ordinal:11 Value:2024-01-17 09:15:02.20918 -0500 EST}], was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
  - matches sql: 'INSERT'
  - is with arguments:
    0 - {}
    1 - {}
    2 - {}
    3 - {}
    4 - {}
    5 - {}
    6 - {}
    7 - {}
    8 - {}
    9 - {}
  - should return Result having:
      LastInsertId: 1
      RowsAffected: 1; call to Rollback transaction, was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
  - matches sql: 'INSERT'
  - is with arguments:
    0 - {}
    1 - {}
    2 - {}
    3 - {}
    4 - {}
    5 - {}
    6 - {}
    7 - {}
    8 - {}
    9 - {}
  - should return Result having:
      LastInsertId: 1
      RowsAffected: 1
[0.507ms] [rows:0] INSERT INTO "ingestable_contracts" ("file_name","merchant_id","merchant","account_number","order_number","jdata","status","step_name","meta","errors","created_at") VALUES ('manual_occurrence','','ashret','','','null','Processing','expand_ingestable','null','null','2024-01-17 09:15:02.209') RETURNING "id"
```

Passes when using `ExpectQuery`

When `ID` is a `string` tests using `ExpectQuery` on `Create` fail:

```
"merchant","account_number","order_number","jdata","status","step_name","meta","errors","created_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)' with args [{Name: Ordinal:1 Value:} {Name: Ordinal:2 Value:manual_occurrence} {Name: Ordinal:3 Value:} {Name: Ordinal:4 Value:ashret} {Name: Ordinal:5 Value:} {Name: Ordinal:6 Value:} {Name: Ordinal:7 Value:null} {Name: Ordinal:8 Value:Processing} {Name: Ordinal:9 Value:expand_ingestable} {Name: Ordinal:10 Value:null} {Name: Ordinal:11 Value:null} {Name: Ordinal:12 Value:2024-01-17 09:36:24.808488 -0500 EST}], was not expected, next expectation is: ExpectedQuery => expecting Query, QueryContext or QueryRow which:
  - matches sql: 'INSERT'
  - is with arguments:
    0 - {}
    1 - {}
    2 - {}
    3 - {}
    4 - {}
    5 - {}
    6 - {}
    7 - {}
    8 - {}
    9 - {}
    10 - {}
    11 - {}
  - should return rows:
    row 0 - [1]; call to Rollback transaction, was not expected, next expectation is: ExpectedQuery => expecting Query, QueryContext or QueryRow which:
  - matches sql: 'INSERT'
  - is with arguments:
    0 - {}
    1 - {}
    2 - {}
    3 - {}
    4 - {}
    5 - {}
    6 - {}
    7 - {}
    8 - {}
    9 - {}
    10 - {}
    11 - {}
  - should return rows:
    row 0 - [1]
[0.278ms] [rows:0] INSERT INTO "ingestable_contracts" ("id","file_name","merchant_id","merchant","account_number","order_number","jdata","status","step_name","meta","errors","created_at") VALUES ('','manual_occurrence','','ashret','','','null','Processing','expand_ingestable','null','null','2024-01-17 09:36:24.808')
```

But passes using `ExpectExec`.

All this makes sense now that I understand the behavior but cryptic for sure.
