### ISSUE TITLE
Unable to mock results with datetime columns

### ISSUE THREAD

**Issue by rvmishra** [DATA-DOG/go-sqlmock#119]
Hey!

Related to #1 

Is this #1 not resolved? I do not see RowFromInterface in [rows.go](https://github.com/DATA-DOG/go-sqlmock/blob/master/rows.go)

I am facing this problem when mocking mysql.

**Comment by l3pp4rd** [comment]
Hi, I've decided to leave this to users. There are many types of data, which could be translated using reflect and whatever. If the library starts to implement those, it will never finish and will start to conflict in implementation wanted.

So I suggest you to have your own method like `AppendRow(rows *sqlmock.Rows, args ...interface{})` under the hood you just call `rows.AddRow(argsTranslatedWhicheverWayYouPrefer ...driver.Value)`

The reason why I do not want to support any `time.Time` translations in sqlmock is that databases support custom formats and sqlmock cannot know which one you actually prefer

**Comment by Nibba2018** [comment]
Hi @l3pp4rd , are you aware of any existing code snippets for `time.Time`?
