### ISSUE TITLE
Question: Is sqlmock capable of finding syntax errors ?

### ISSUE THREAD

**Issue by kerak19** [DATA-DOG/go-sqlmock#121]
Let's say someone sloppy left floating semicolon inside of query. Is there any way for sqlmock to detect it and return error?

Thanks.

**Comment by l3pp4rd** [comment]
Hi, no, that is why you also do functional tests, sqlmock is only for unit tests and it is not supposed to match whole query string, matching part of it makes more sense, less maintenance when field changes or whatever.
