### ISSUE TITLE
Unable to mock `Select 'x' ` query

### ISSUE THREAD

**Issue by Yuddistira** [DATA-DOG/go-sqlmock#125]
So I am using this query : 
`select 'x' from a_table where id = $1`

In unit test : 
`sqlmock.ExpectQuery("SELECT 'x' FROM a_table(.+)").
WithArgs(1).WillReturnRows(sqlmock.NewRows([]string{"x"}).AddRow(12345))`

But what i get is error without result.
What is the correct way to mock `Select 'x'` ?

Thank you very much.

(Sorry, i am not english native speaker)

**Comment by l3pp4rd** [comment]
Hi, sqlmock uses regular expression, so you can check whether it matches properly. by just running a small test

and it is case sensitive, see it in [playground](https://play.golang.org/p/wO6TfxH-6Aw)

You should figure out these on your own without opening an issue, cheers
