### ISSUE TITLE
Scan error with NullInt64

### ISSUE THREAD

**Issue by raymontag** [DATA-DOG/go-sqlmock#131]
I have a model which uses NullInt64 for the ID like in the following example:

    type Customer struct {
	    ID        NullInt64 `gorm:"primary_key" json:"id"`
	    Password  string    `json:"password"`
    }

However, I get the following error if I mock this:

    sql: Scan error on column index 0: converting driver.Value type main.NullInt64 ("{1 true}") to a int64:      invalid syntax

I guess that the driver does not implement NullInt64 as a named value. It would be nice if one could do this by oneself.

**Comment by l3pp4rd** [comment]
@dolmen can it be related to recent change?

**Comment by l3pp4rd** [comment]
Hi @raymontag does the NullInt64 implement [sql.driver.Valuer](https://golang.org/pkg/database/sql/driver/#Valuer) the recent change in sqlmock forced the sql driver value convertion, which restricts mocking rows to proper sql driver values.

**Comment by raymontag** [comment]
@l3pp4rd Yes it does:


    func (nullInt64 NullInt64) Value() (driver.Value, error) {
	    if !nullInt64.Valid {
		    return nil, nil
	    }
	    return nullInt64.Int64, nil
    }

**Comment by l3pp4rd** [comment]
interesting, will need to add a test and see, thanks for reporting

**Comment by l3pp4rd** [comment]
the test added works as expected, is the type you use implement sql.Scanner interface? could you show me a failing code example?

**Comment by dolmen** [comment]
Your `NullInt64` type should also implement `sql.Scanner`, like the original [`sql.NullInt64`](http://localhost:6060/pkg/database/sql/#NullInt64) (see [source](https://golang.org/src/database/sql/sql.go?s=5507:5595#L228))

But if you are on Go 1.9+ you should probably just use a [type alias](https://golang.org/doc/go1.9#language) in your package:
```go
type NullInt64 = sql.NullInt64
```
