### ISSUE TITLE
Feature: Allow exceptions to be cleared/fulfilled

### ISSUE THREAD

**Issue by bwjohnson-ss** [DATA-DOG/go-sqlmock#132]
I'm using sqlmock to run some tests, and I've structured the tests is in a way such that I'd like to re-use the mock objects across each of the tests, instead of creating new mocks for each and every test. If all the tests pass fine, then all is well, but if one of the tests fail because of unmet expectations, then each subsequent test will also fail too.

I was wondering if you would be ok with adding a public interface method to allow the list of expectations to be cleared. Something like this:

```
func (c *sqlmock) ClearAllExpectations() {
	for _, e := range c.expected {
		e.SetFulfilled()
	}
}

func (e *commonExpectation) SetFulfilled() {
	e.triggered = true
}
```

**Comment by l3pp4rd** [comment]
Hi, short answer - no. if you wish to have `assertTrue(true)` kind of tests, you are welcome to fork it and change whatever way you prefer. There are other options, like in your test.go files you can add a mini framework on top to produce expected queries using short keywords with minimized arguments.

**Comment by bwjohnson-ss** [comment]
Can you please explain more about what you mean by `assertTrue(true)` kind of tests? If I understand you correctly, I think I've already built a _mini framework_ to minimize the boilerplate testing code, but I want to make sure we're on the same page. Is there a style/tech reason why you wouldn't want to add something like this? I'm trying to understand the philosophy/rationale behind it. Thanks.
