### ISSUE TITLE
mysql: Conflict when Scanning into pointers to interfaces

### ISSUE THREAD

**Issue by OrenRosen** [DATA-DOG/go-sqlmock#133]
When scanning sql.Raws into pointers to interfaces, mysql returns a byte array, (or if setting parseTime=true, returns a time.Time on data fields).
So to get a string value from a result, need first to cast it to []byte
```
	pointers := make([]interface{}, len(cols))
	container := make([]interface{}, len(cols))
	for i, _ := range cols {
		pointers[i] = &container[i]
	}

	if err := rows.Scan(pointers...); err != nil {
		return nil
	}

	r := make(map[string]interface{})
	for i, col := range cols {
		r[col] = container[i]
	}

	return r
```
parsing it into int:
```
lastName := string(result["last_name"].([]byte)[:])
```

On the other hand, when mocking an expectation with sqlmock, it returns a string, and not []byte, so the casting to []byte will fail
```
mock.ExpectQuery("SELECT").WithArgs("Some Name").
	WillReturnRows(sqlmock.NewRows([]string{"last_name"}).AddRow("Some Last Name"))
```

We have couple of workarounds, like encode the string in the expectation, or checking the type when parsing, but wanted to know if there is some native solution for this case.
Thanks

**Comment by l3pp4rd** [comment]
Hi, currently in recent commits, there was a patch, that every row value is converted to driver value, see line https://github.com/DATA-DOG/go-sqlmock/blob/master/rows.go#L132

That conversion supports [driver.Valuer](https://golang.org/pkg/database/sql/driver/#Valuer) so if your sql driver has such converters packaged inside, you can use them to create Rows. If you want your strings translated to bytes, build rows with bytes. driver.Value supports string and bytes, so it cannot know what you will want exactly, there is no translation done here.

**Comment by OrenRosen** [comment]
yep, this is what I figured
Thanks a lot!
