### ISSUE TITLE
Convert to xorm.Engine

### ISSUE THREAD

**Issue by happilymarrieddad** [DATA-DOG/go-sqlmock#136]
Hey guys,

Is there an easy way to convert the sql.Db to xorm.Engine so I can easily use this for go testing.

![selection_054](https://user-images.githubusercontent.com/6416323/44486152-04803a00-a610-11e8-8d11-b3afab455f20.png)
![selection_055](https://user-images.githubusercontent.com/6416323/44486161-0649fd80-a610-11e8-8d01-d6756cb903b6.png)
![selection_056](https://user-images.githubusercontent.com/6416323/44486162-08ac5780-a610-11e8-9d3d-f74cb7b43216.png)

```
cannot use db (type *sql.DB) as type *"github.com/fusionwarellc/api.fusionware.com/vendor/github.com/go-xorm/xorm".Engine in argument to Delete
db *DB
```

**Comment by l3pp4rd** [comment]
Hi, if xorm.Engine uses the `sql.driver` package, then you are all set, just initialize it with correct dsn

**Comment by happilymarrieddad** [comment]
Thanks!

engine.DB().db = db
