### ISSUE TITLE
Bug on trying to return no rows

### ISSUE THREAD

**Issue by MikeWarren2014** [DATA-DOG/go-sqlmock#137]
In a func under test, there's an SQL query that's to check for a row satisfying some user-defined conditions.
The code for that query is thus: 

```
fmt.Sprintf(`
SELECT true
FROM %s
WHERE %s
`, tableName, strings.Join(andConditions, " AND "))
```

where `andConditions` is a `[]string`. 
My test for it, in the case of "no match", fails. 

**Debugging time**
To debug it, I write a test that invokes the query directly: 

```
t.Run("FrameworkSanityTest", func(t *testing.T) {
		mock.ExpectQuery(regex).
			WillReturnError(sql.ErrNoRows)
		rows, _ := db.Query(`SELECT true
		FROM employees
		WHERE emp_name = Zack Taylor`)
		n := 0
		var val interface{}
		for rows.Next() {
			n++
			rows.Scan(&val)
		}

		mock.ExpectationsWereMet()

		assert.False(t, rows.Next())  // fails
		assert.Empty(t, val)  // also fails, because somehow, val == true
	})
```

where `regex := "SELECT true(\\n| )FROM employees(\\n| )WHERE (.+)"`

Notice the behavior specification: 
`mock.ExpectQuery(regex).WillReturnError(sql.ErrNoRows)`

This fails even if I change it to `mock.ExpectQuery(regex).WillReturnRows(sqlmock.NewRows(columns))`

**Comment by MikeWarren2014** [comment]
I fail to see what that has to do with the actual issue at hand here. Also, I'm not responsible for maintaining the code under test. That query came from the code under test.

**Comment by l3pp4rd** [comment]
have you checked the error? it may fail because it cannot match the regexp. sqlmock is widely used and the error is not in the library, but rather on mock you are using

**Comment by MikeWarren2014** [comment]
I seem to be getting inconsistent results. As of the time I posted, this, I got a fail on the following assertions: 

```
assert.False(t, rows.Next())  // fails
assert.Empty(t, val)  // also fails, because somehow, val == true
```

There's nothing in the output about the expectations failing.

**Comment by MikeWarren2014** [comment]
The test itself passes, when I comment out the failing test right above it, but when I uncomment it, I get panic, on the line `for rows.Next()`

**Comment by l3pp4rd** [comment]
I do not have time to guide you\, try asking on stackoverflow you may get help there way faster.
