### ISSUE TITLE
Expectations on mock not getting reset at the beginning of each test

### ISSUE THREAD

**Issue by MikeWarren2014** [DATA-DOG/go-sqlmock#138]
[There was previous issue](https://github.com/DATA-DOG/go-sqlmock/issues/137) I had, which seemed to be just weakness of the framework, but there was another fail regarding [multiple valid test cases ](https://stackoverflow.com/questions/52011146/similar-sqlmock-expectations-from-multiple-test-cases-causing-false-fails)in the same test. 

**Code Under Test**
 is defined thus: 

```
//Transaction Begins a sql transaction.
func Transaction(db *sql.DB, txFunc func(*sql.Tx) *errors.ErrorSt) (retErrSt *errors.ErrorSt) {
	retErrSt = nil
	tx, retErrSt := beginTrans(db)
	if retErrSt != nil {
		return retErrSt
	}

	defer func() {
		if p := recover(); p != nil {
			tx.Rollback()
			panic(p) // re-throw panic after Rollback
		} else if retErrSt != nil {
			tx.Rollback()
		} else {
			if err := tx.Commit(); err != nil {
				retErrSt = errors.Database().AddDetails(err.Error())
			}
		}
	}()
	retErrSt = txFunc(tx)
	return retErrSt
}
```

**Setup logic**

```
// database mock/stub setup
	db, mock, err := sqlmock.New()
	if !assert.Nilf(t,
		err,
		"Error on trying to start up a stub database connection") {
		t.Fatal()
	}
	defer db.Close()
```

**First Test**

```
t.Run("WantCommitError", func(t *testing.T) {
		// define sql behavior
		mock.ExpectBegin()

		err := Transaction(db,
			func(tx *sql.Tx) *errors.ErrorSt {
				return nil
			})

		defer func() {
			mock.ExpectCommit().
				WillReturnError(goErrors.New("test commit error"))
			assert.Equal(t,
				string(errors.ACDatabase),
				err.Code)
		}()

		mock.ExpectationsWereMet()

	})
```

**Second Test**
```
t.Run("WantErrorFromCallback", func(t *testing.T) {
		mock.ExpectBegin()

		err := Transaction(db,
			func(tx *sql.Tx) *errors.ErrorSt { return new(errors.ErrorSt) })

		defer func() {
			mock.ExpectRollback()
		}()
		mock.ExpectationsWereMet()

		if !assert.Equal(t, new(errors.ErrorSt), err) {
			t.Error(err.ToString(false))
		}
	})
```

Running either test by itself results in no issues. But issues happen when I run them both (See the second link, the link to the StackOverflow question for more details. I'm basically repeating what I said there, here.)

**Comment by MikeWarren2014** [comment]
I was able to fix at least this use case on my own:

I used [testify's suites](https://godoc.org/github.com/stretchr/testify/suite) for all my test cases against the func,  putting the `ExpectationsWereMet()` in the func being `defer`red.

Is that how I must use this whenever it comes up: just use the suites? (Instinct, especially from Java, tells me to do so, but idk if that is how we fix this stale mock state issue.)

**Comment by MikeWarren2014** [comment]
The issue came back [in a different use case](https://stackoverflow.com/questions/52065102/one-test-causing-another-to-fail)

**Comment by l3pp4rd** [comment]
Hi, in every test scenario, sqlmock expects to start with freshly created mock. if you will have unmatched expectations remaining, it will certainly fail on next test

**Comment by MikeWarren2014** [comment]
In [the current use case](https://stackoverflow.com/questions/52065102/one-test-causing-another-to-fail), there's nothing in the error log about any unmatched expectations. Even worse is when I `assert.NoError(t, suite.mock.ExpectationsWereMet)`, there's no additional fails (meaning the expectations were met), and all the functions under test require w.r.t. db objects is a `sql.Rows` to act on.

I think my biggest issue here is in trying to use this mocking framework as a stubbing one to create test doubles. 

The methods I'm trying to test :

```
// ReadFrom reads values from `rows` into `valuePlaceholders`
func ReadFrom(rows *sql.Rows,
	readerFunc func(rowIndex int, readValues ...interface{}) (bool, *errors.ErrorSt),
	valuePlaceholders ...interface{}) (err *errors.ErrorSt) {

	rowLine := 1
	for rows.Next() {
		if err := rows.Scan(valuePlaceholders...); err != nil {
			return errors.Database().AddDetails(err.Error(), valuePlaceholders)
		}
		if readerFunc != nil {
			skipRest, err := readerFunc(rowLine, valuePlaceholders...)
			if err != nil {
				return err
			}
			if skipRest {
				break
			}
		}
		rowLine++
	}
	if rowLine == 1 {
		return errors.Get(appErrors.ACNoRows)
	}
	return nil
}

//**************************************************************************
//SQLRowsToJSON Converts rows dataset into json to transfer
//
// Parameters:
// - `rows`
//
// Returns:
// - JSON stringification of `rows`
// - any errors that happened in the process
func SQLRowsToJSON(rows *sql.Rows) (string, *errors.ErrorSt) {
	jsonRes, err := json.Marshal(rows)
	if err != nil {
		return "", errors.JSON().AddDetails(err.Error())
	}
	return fmt.Sprint(jsonRes), nil
}

//**************************************************************************
//SQLRowsTo2DArray Converts rows dataset into 2D array
func SQLRowsTo2DArray(rows *sql.Rows) ([][]interface{}, *errors.ErrorSt) {
	result := make([][]interface{}, 0)
	cols, _ := rows.Columns()
	valuesArr := make([]interface{}, len(cols))
	valuesPtrArr := utilities.ValArrToPointerArr(valuesArr)

	readLineFunc := func(rowIndex int, readValues ...interface{}) (bool, *errors.ErrorSt) {
		valuesArr2 := make([]interface{}, len(cols))
		copy(valuesArr2, valuesArr)
		result = append(result, valuesArr2)
		return false, nil
	}

	if err := ReadFrom(rows, readLineFunc, valuesPtrArr...); err != nil {
		return nil, err
	}
	return result, nil
}
```

**Comment by l3pp4rd** [comment]
if this framework does not work fir you, use something else. I do not have time to read your code. if you find a bug, submit a failing test case.
