### ISSUE TITLE
How to test INSERT statement?

### ISSUE THREAD

**Issue by jamesbloomer** [DATA-DOG/go-sqlmock#14]
In my code: 

```_, err = db.Exec("INSERT INTO mytable(a, b) VALUES(?,?)```

and in my test:

```
sqlmock.ExpectExec("INSERT INTO mytable(a,b)")
             .WithArgs("A", "B")
            ....
```

But I get the message:

```
INSERT INTO mytable(a, b) VALUES(?,?) does not match regex INSERT INTO mytable(a,b)
```

I've tried adding the values to the expectation parameters and escaping the question marks but with no joy. Is this possible?

**Comment by l3pp4rd** [comment]
Hi, **does not match regex** in the error message is straight forward. It matches a pattern as a regular expression, escape the parenthesis and question marks..

**Comment by l3pp4rd** [comment]
I will add a test case just for the sake of interest :)

**Comment by jamesbloomer** [comment]
Yeah, that's great thanks, I forgot to escape the brackets.
