### ISSUE TITLE
False passing of ExpectExec

### ISSUE THREAD

**Issue by willis7** [DATA-DOG/go-sqlmock#143]
This could be a fundamental misunderstanding of the framework, or a real bug.

**Code under test**
``` go
type repository struct {
	db *sqlx.DB
}

func (r repository) Create(environment Environment) error {
	tx := r.db.MustBegin()
	tx.NamedExec("INSERT INTO environment (name) VALUES (:name)", environment)
	return tx.Commit()
}
```

**Test**
``` go
func TestRepository_Create(t *testing.T) {
	mockDB, mock, err := sqlmock.New()
        defer mockDB.Close()
	db := sqlx.NewDb(mockDB, "sqlmock")

	repo := repository{
		db: db,
	}

	mock.ExpectBegin()
	mock.ExpectExec("garbage").WithArgs("test store")
	mock.ExpectCommit()

	repo.Create(Environment{Name: "foo"})
}
```

I would expect `mock.ExpectExec("garbage")` to fail, but it passes every time.

**Comment by l3pp4rd** [comment]
Hi, in go errors need to be checked, read the examples and look at the test files, in this case NamedExec fails with an error because the sql.Result is not mocked and you do not check errors. read examples to understand the library you are using before asking any questions

**Comment by willis7** [comment]
This was a lack of understanding on my part. Closing
