### ISSUE TITLE
Add ExpectPing() to Sqlmock interface

### ISSUE THREAD

**Issue by dhui** [DATA-DOG/go-sqlmock#149]
I noticed that https://github.com/DATA-DOG/go-sqlmock/pull/68 mentions that there's no `ExpectPing()` since it's not backwards compatible.

Can `ExpectPing()` be added now that Go 1.9 (soon to be Go 1.10) is the [oldest supported release](https://golang.org/doc/devel/release.html#policy)?

**Comment by l3pp4rd** [comment]
Hi, likely will need to revisit this.

**Comment by Melaninneal** [comment]
Bumping this

**Comment by dhui** [comment]
Looks like this is fixed by https://github.com/DATA-DOG/go-sqlmock/pull/204

**Comment by dhui** [comment]
Any chance of cutting a new release soon? The master branch seems to work fine for my usage.

**Comment by l3pp4rd** [comment]
done
