### ISSUE TITLE
Expect Close to be called

### ISSUE THREAD

**Issue by karlkfi** [DATA-DOG/go-sqlmock#15]
It'd be nice if the mock rows struct would expect Close() to be called, either by default or with an ExpectClose() enabler. Most of the time the closing is deferred, but we want to test that it happens.

**Comment by l3pp4rd** [comment]
sounds reasonable, will have a look when I have some time

**Comment by l3pp4rd** [comment]
since this will not be backward compatible, will add this to the milestone, should go with a version change
