### ISSUE TITLE
MatchExpectationsInOrder(false) seems not to work in ExpectPrepare

### ISSUE THREAD

**Issue by omrsin** [DATA-DOG/go-sqlmock#153]
The following code can be used to reproduce the behavior

```
import (
	"fmt"
	"testing"

	"gopkg.in/DATA-DOG/go-sqlmock.v1"
)

func TestOrdering(t *testing.T) {
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fail()
	}

	mock.MatchExpectationsInOrder(false)

	mock.ExpectPrepare(fmt.Sprintf("select (.+) from A"))
	mock.ExpectPrepare(fmt.Sprintf("select (.+) from A where (.+)"))
	mock.ExpectPrepare(fmt.Sprintf("delete from A where (.+)"))

	queries := map[int]string{
		0: `select x from A`,
		1: `select x from A where y = ?`,
		2: `delete from A where x = ?`,
	}

	for _, query := range queries {
		_, err := db.Prepare(query)
		if err != nil {
			t.Error(err)
		}
	}
}
```
In this example, the preparation of the statements is done after ranging over a map. There are no assumptions about the order of this range so the statements can be prepared in any order. It seems that deactivating the check for matching expectations in order does not affect this case. Please execute the tests several times in order to trigger the non-deterministic behavior.

**Comment by l3pp4rd** [comment]
thanks for report, will add it to check list, unless you want to contribute that change?

**Comment by l3pp4rd** [comment]
Hi, it does not seem to be a bug, the problem is that the first regexp for prepare statement can match both queries 0 and 1 in the map. so if map range goes picking the query under 1 key, it will match it with first mock. then if it will pick 0 key next there won't be any match.
