### ISSUE TITLE
Is possible to ignore the argument matching?

### ISSUE THREAD

**Issue by fernandoabolafio** [DATA-DOG/go-sqlmock#157]
I have a part of my testing code which matches a query and one of the arguments is a encrypted value which leads to a different output every time I run the encryption.
In summary what I need is a way to ignore the matching of that argument because I cannot foresee what will be the value.
Something like: 
```Go
mock.ExpectQuery("`UPDATE "key_value" SET "payload" = $1`").SkipArgumentsMatching()`
```

I know the option above is not possible. Is there any workaround for this though?

**Comment by l3pp4rd** [comment]
Hi, no sqlmock does not allow to skip argument matching. but you can have custom argument matcher, see `sqlmock.Argument` and `sqlmock.AnyArg()`

**Comment by fernandoabolafio** [comment]
@l3pp4rd thanks for the quick reply. I did the following:
```Go
type EncryptedPayload struct{}

// XXX need to improve this match
func (e EncryptedPayload) Match(v driver.Value) bool {
	return true
}

(*mock).ExpectQuery(fixedFullRe(`UPDATE "key_value" SET "payload" = $1`)).WithArgs(EncryptedPayload{})
```

And I am still getting this error:
```
 call to ExecQuery 'UPDATE "key_value" SET "payload" = $1' with args [{Name: Ordinal:1 Value:[115 ... 58]}], was not expected, next expectation is: ExpectedQuery => expecting Query, QueryContext or QueryRow which:
          - matches sql: 'UPDATE "key_value" SET "payload" = $1'
          - is with arguments:
            0 - {}
```

Do you have any idea why is it still failing?

**Comment by l3pp4rd** [comment]
you are expecting a Query, but actualy Exec is done, so it is a different expectation you have to make

**Comment by fernandoabolafio** [comment]
got it, thanks a lot.

**Comment by lsei** [comment]
I ran into a similar issue when writing a test for a database transaction. The test that I am writing simply checks to make sure the transaction began, the start of the relevant execs, and that it is committed at the end. The details of the individual queries are checked in other tests. 

While it's possible to use AnyArg or a custom matcher the argument list still requires the correct amount of arguments which in my case is more detail than I would like that specific test. 

Is there something I'm missing / any workaround ideas to this?

**Comment by afzalabbasi** [comment]
call to Query 'SELECT * FROM permission WHERE roleid = ?' with args [{Name: Ordinal:1 Value:2}], was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
  - matches sql: 'SELECT * FROM permission WHERE roleid = $1'
  - is with  getting this error can some please help me how i fixed this one

**Comment by MarvinKweyu** [comment]
> I ran into a similar issue when writing a test for a database transaction. The test that I am writing simply checks to make sure the transaction began, the start of the relevant execs, and that it is committed at the end. The details of the individual queries are checked in other tests.
> 
> While it's possible to use AnyArg or a custom matcher the argument list still requires the correct amount of arguments which in my case is more detail than I would like that specific test.
> 
> Is there something I'm missing / any workaround ideas to this?

Did you find a workaround for this?
@lsei
