### ISSUE TITLE
New release & modules support

### ISSUE THREAD

**Issue by philtay** [DATA-DOG/go-sqlmock#160]
Could you please cut a new release? Please also add a `go.mod` file in the repository root. Thanks!

**Comment by l3pp4rd** [comment]
hi, is there a sane reason to add `go.mod` if this library has no dependencies?

**Comment by philtay** [comment]
https://github.com/golang/go/wiki/Modules#should-i-still-add-a-gomod-file-if-i-do-not-have-any-dependencies
