### ISSUE TITLE
v1.3.1 Breaks build

### ISSUE THREAD

**Issue by KillerX** [DATA-DOG/go-sqlmock#161]
Any idea what is going on here? This has been happening for us since the 1.3.1 release.

```
go: finding gopkg.in/DATA-DOG/go-sqlmock.v1 v1.3.1
go: gopkg.in/DATA-DOG/go-sqlmock.v1@v1.3.1: go.mod has non-....v1 module path "sqlmock" at revision v1.3.1
```

**Comment by l3pp4rd** [comment]
Hi, most likely something is not right with the module name

**Comment by jrbarron** [comment]
I think the module name in `go.mod` is incorrect. The following change fixes it for me:

```diff
-module sqlmock
+module gopkg.in/DATA-DOG/go-sqlmock.v1
```

**Comment by l3pp4rd** [comment]
is it a good practice to have a `gopkg.in/DATA-DOG/go-sqlmock.v1` gopkg module name? or it should rather be `github.com/DATA-DOG/go-sqlmock` since modules support versioning

**Comment by philtay** [comment]
Initialize `go.mod` with:

```
$ go mod init github.com/DATA-DOG/go-sqlmock
```

You don't need `gopkg.in` at all.

**Comment by l3pp4rd** [comment]
created the [v1.3.2](https://github.com/DATA-DOG/go-sqlmock/releases/tag/v1.3.2) tag, hope that will not cause any more issues

**Comment by philtay** [comment]
@l3pp4rd you can now start to migrate away from `gopkg.in` (if you want). i mean docs, examples, etc...

**Comment by l3pp4rd** [comment]
@philtay would you be kind to create a pull request?

**Comment by philtay** [comment]
@l3pp4rd I can't right now, but the commands below should be enough:

```
$ sed -i 's/gopkg.in\/DATA-DOG\/go-sqlmock.v1/github.com\/DATA-DOG\/go-sqlmock/g' <files ... e.g. README.md>
$ git commit -a -m "Hello SemVer!"
$ git push
```

**Comment by smadbe** [comment]
Seems to work, do not forget to fix the README as well to use `github.com/DATA-DOG/go-sqlmock` (`go get` and `import (...)`).

**Comment by dolmen** [comment]
Thanks for breaking all our go.mod files.

**Comment by dolmen** [comment]
On Mac, here is the fixed `sed` command to change import path:
```
$ sed -i '' 's/gopkg.in\/DATA-DOG\/go-sqlmock.v1/github.com\/DATA-DOG\/go-sqlmock/g' *.go
```

**Comment by philtay** [comment]
@dolmen You're welcome!
