### ISSUE TITLE
GoModules naming problem

### ISSUE THREAD

**Issue by im-kulikov** [DATA-DOG/go-sqlmock#166]
```
→ go get -u gopkg.in/DATA-DOG/go-sqlmock.v1
go: gopkg.in/DATA-DOG/go-sqlmock.v1@v1.3.2: go.mod has non-....v1 module path "github.com/DATA-DOG/go-sqlmock" at revision v1.3.2
go: error loading module requirements
```

Problem with module naming [here](https://github.com/DATA-DOG/go-sqlmock/blob/3f9954f6f6697845b082ca57995849ddf614f450/go.mod#L1) from [commit](
https://github.com/DATA-DOG/go-sqlmock/commit/472e287dbafe67e526a3797165b64cb14f34705a) 

```go.mod
module github.com/DATA-DOG/go-sqlmock
```

In [documentation](https://github.com/DATA-DOG/go-sqlmock/tree/v1.3.2#install):
```
go get gopkg.in/DATA-DOG/go-sqlmock.v1
```

**Comment by l3pp4rd** [comment]
Hi, yes this was misleading, since the tag was created before renaming. Just recently made another tag `v1.3.3` in order to prevent these misunderstandings in the future, caused by migration to module.

**Comment by im-kulikov** [comment]
Thanks..

**Comment by jeffreylo** [comment]
I think this is still an issue.

```
λ go get -u gopkg.in/DATA-DOG/go-sqlmock.v1
go: gopkg.in/DATA-DOG/go-sqlmock.v1@v1.3.3: go.mod has non-....v1 module path "github.com/DATA-DOG/go-sqlmock" at revision v1.3.3
go get: error loading module requirements
```

**Comment by l3pp4rd** [comment]
Hi @jeffreylo we cannot rely making module name as gopkg.in, that service may just go away any time. Use `github.com/DATA-DOG/go-sqmock` for go get and anything else.
