### ISSUE TITLE
v2 vs master

### ISSUE THREAD

**Issue by pjebs** [DATA-DOG/go-sqlmock#168]
I was wondering what the difference was between v2 branch and master branch?

**Comment by pjebs** [comment]
master still says v1, yet is updated more regularly.

**Comment by l3pp4rd** [comment]
Hi, v2 was branched off for backward incompatible changes, which may or may not later go to master and be a part of v2. so far it is not reasonable to have these changes and better stay backward compatible so users do not experience any issues updating. But if some changes over time will accumulate in v2 and will be worth merging, then we will consider bumbing version to v2.0.0
