### ISSUE TITLE
whether sqlmock can mock NoSQL，like mongodb、redis？

### ISSUE THREAD

**Issue by justinling89** [DATA-DOG/go-sqlmock#170]
whether sqlmock can mock NoSQL，like mongodb、redis？

**Comment by l3pp4rd** [comment]
Sqlmock only works with **database/sql** if your nosql library implements fully sql driver from standard library then yes

**Comment by justinling89** [comment]
> Sqlmock only works with **database/sql** if your nosql library implements fully sql driver from standard library then yes

so how can i judge whether my nosql library implements fully sql driver？thanks！
