### ISSUE TITLE
sql.RawBytes scan destination does not share database memory

### ISSUE THREAD

**Issue by dackroyd** [DATA-DOG/go-sqlmock#176]
```
// RawBytes is a byte slice that holds a reference to memory owned by
// the database itself. After a Scan into a RawBytes, the slice is only
// valid until the next call to Next, Scan, or Close.
type RawBytes []byte
```

With go-sqlmock, the memory scanned into `sql.RawBytes` remains unaffected by any subsequent `Next()`, `Scan()` or `Close()`. As a result, this memory is safer than intended, and hides bugs that occur when using other database drivers (e.g. in when running in production)

Example:

Note that I've overwritten the memory allocated into the `sql.RawBytes` values with a repeating `☠☠☠ MEMORY OVERWRITTEN ☠☠☠` to fill the slice. The intention here is to make it obvious when the values are used incorrectly, rather than overwriting with other shared memory from subsequent rows, which would be far more subtle and harder to understand.

```
func ExampleRows_rawBytes() {
	db, mock, err := New()
	if err != nil {
		fmt.Println("failed to open sqlmock database:", err)
	}
	defer db.Close()

	rows := NewRows([]string{"id", "binary"}).
		AddRow(1, []byte(`one binary value with some text!`)).
		AddRow(2, []byte(`two binary value with even more text than the first one`))

	mock.ExpectQuery("SELECT").WillReturnRows(rows)

	rs, _ := db.Query("SELECT")
	defer rs.Close()

	type scanned struct {
		id  int
		raw sql.RawBytes
	}
	fmt.Println("initial read...")
	var ss []scanned
	for rs.Next() {
		var s scanned
		rs.Scan(&s.id, &s.raw)
		ss = append(ss, s)
		fmt.Println("scanned id:", s.id, "and raw:", string(s.raw))
	}

	if rs.Err() != nil {
		fmt.Println("got rows error:", rs.Err())
	}

	fmt.Println("after reading all...")
	for _, s := range ss {
		fmt.Println("scanned id:", s.id, "and raw:", string(s.raw))
	}
	// Output:
	// initial read...
	// scanned id: 1 and raw: one binary value with some text!
	// scanned id: 2 and raw: two binary value with even more text than the first one
	// after reading all...
	// scanned id: 1 and raw: ☠☠☠ MEMORY OVERWRITTEN ☠
	// scanned id: 2 and raw: ☠☠☠ MEMORY OVERWRITTEN ☠☠☠ ☠☠☠ MEMORY
}
```

The output that is actually produced here retains the original scanned values for the `sql.RawBytes` fields even after the scan loop (which invokes `rs.Next()`)

Actual output:

```
initial read...
scanned id: 1 and raw: one binary value with some text!
scanned id: 2 and raw: two binary value with even more text than the first one
after reading all...
scanned id: 1 and raw: one binary value with some text!
scanned id: 2 and raw: two binary value with even more text than the first one
```

**Comment by l3pp4rd** [comment]
Sqlmock is a pure mocking driver, only meant to be used in tests. It is fully the responsibility of the user, how he mocks the sql responses. What do you expect?

**Comment by dackroyd** [comment]
It's not possible (from what I can tell) to reproduce the shared memory (and the issues it causes when misusing it) via `go-sqlmock` with the existing implementation. If we are ultimately scanning into a `sql.RawBytes` value, ideally it should be upholding the documented behaviour for that type, specifically:

> the slice is only valid until the next call to Next, Scan, or Close.

The expectation when `sql.RawBytes` is used as a scan destination is for the memory to be copied out of that shared memory _before_ any calls to Next, Scan, or Close.

https://github.com/golang/go/issues/22039#issuecomment-340843124

> So if you use RawBytes and you don't copy it out yourself, you're not working with it correctly.

Because `go-sqlmock` doesn't invalidate the slice's content when these things occur, incorrectly using the value isn't exposed via tests. How I'd want this to behave is for the slice content to be invalidated (as per the docs for `sql.RawBytes`), allowing unit tests utilising `go-sqlmock` to fail if the value is used incorrectly.

**Comment by l3pp4rd** [comment]
well I agree, we could implement that invalidation of the slice whenever rows next or scan is processed. are you willing to contribute that part?

**Comment by dackroyd** [comment]
I'd be happy to 😃 

I've already worked on getting something going (the example from earlier is copy-pasted from that), but I need to work on additional tests for the behaviour, in particular `[]byte` vs `sql.RawBytes` vs other aliases of `[]byte`

**Comment by l3pp4rd** [comment]
good, thanks !
