### ISSUE TITLE
Support for INSERT with 3 or more question marks.

### ISSUE THREAD

**Issue by freshteapot** [DATA-DOG/go-sqlmock#179]
Great library!

Little issue with ExpectPrepare and ExpectExec

```
INSERT INTO example (user, firstname, surname) VALUES (?, ?, ?)
```

Causes

```
Prepare: error parsing regexp: invalid or unsupported Perl syntax: `(?,
```

I can get around it with

```
INSERT INTO example (.+) VALUES (.+)
```
However I then dont get the great joy of knowing the sql matches exact.

**Comment by freshteapot** [comment]
I solved this by using

```
db, mock, err := sqlmock.New(sqlmock.QueryMatcherOption(sqlmock.QueryMatcherEqual))
```

as mentioned in the Readme, but it wasnt obvious.

Very pleased to be able to rely on the exact query again :).

**Comment by l3pp4rd** [comment]
Hi, the default is regular expression matcher to stay backward compatible. Cheers
