### ISSUE TITLE
ExpectRollback doesn't trigger

### ISSUE THREAD

**Issue by brunoqc** [DATA-DOG/go-sqlmock#18]
I'm not sure if I'm doing this right but ExpectRollback doesn't trigger in this case :

```go
func TestRollback(t *testing.T) {
	db, err := sqlmock.New()
	if err != nil {
		t.Errorf("an error '%s' was not expected when opening a stub database connection", err)
	}

	sqlmock.ExpectBegin()
	sqlmock.ExpectRollback()

	_, errBegin := db.Begin()
	if errBegin != nil {
		t.Fatal(errBegin)
	}

	err = db.Close()
	if err == nil {
		t.Fail()
	}
}
```

**Comment by l3pp4rd** [comment]
hm, the rollback is triggered directly by `db.Rollback()` if you close database connection I'm quite sure, that database handles that internally - a transaction started by the closed connection should be rolled back.

**Comment by brunoqc** [comment]
OK thanks.
