### ISSUE TITLE
WillReturnResult() always evaluating true

### ISSUE THREAD

**Issue by jamiebarnett** [DATA-DOG/go-sqlmock#181]
No matter what values I pass to `WillReturnResult()` via `NewResult()`, expectations are always met. I am convinced I am doing something wrong, however my code seems to align with the example in the [godoc](https://godoc.org/github.com/DATA-DOG/go-sqlmock#example-NewResult) and the `WithArgs()` functions are catching missing/incorrect args as expected.

```
db, mock, err := sqlmock.New()
if err != nil {
	t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
}
defer db.Close()

rc := repoClient{
	db: db,
}

mock.ExpectExec("INSERT (.+)").
	WithArgs(test.args...).
	WillReturnResult(sqlmock.NewResult(10, 1000)) // expecting 1 row to be affected but any combination of values I have tried is meeting expectations
mock.ExpectExec("UPDATE (.+)").WithArgs(nil).
	WillReturnResult(sqlmock.NewResult(30, 30)) // expecting no rows to be  affected here and same issue
				
// function under test
err = rc.Update(url)
if err != nil {
	t.Errorf("expected no error but got : %+v", err)
}

if err := mock.ExpectationsWereMet(); err != nil {
	t.Errorf("There were unfulfilled expectations: %s", err)
}
```

Any help would be greatly appreciated!

Thanks

**Comment by l3pp4rd** [comment]
Hi, how does `rc` know which database to use? can you show the full code snippets for method you are testing and the test itself? WillReturnResult always returns the given result if query is matched. If your result depends on the arguments you get to that query, in that case you need to match the query arguments well, and based on it return the different result.
Maybe your code exactly performs the same on different conditions. Sqlmock is functioning correctly,. the only problem may be in your code or mocking.

**Comment by jamiebarnett** [comment]
Thanks for your reply. `rc`  is initialised with the mock db instance, I have updated my above comment with the full code snippet. OK thanks I will continue to investigate.
