### ISSUE TITLE
Is it safe to use a global sqlmock for several tests?

### ISSUE THREAD

**Issue by JairoGLoz** [DATA-DOG/go-sqlmock#182]
Let's say I'm creating tests for two db methods, and both methods need to **prepare** and then **execute** an update query. I have separated tests for each method. Should I create a new sql mock for each test?  or can I create a global mock and use it in all my tests? what happens if I have a single mock and, since go runs tests concurrently, one test is waiting for a **prepare** statement to be called while another test calls _ExpectationsWereMet()_ on that same mock? I think this would cause the test to fail, right? Maybe I'm pretty much answering my own question but I'd like to get a confirmation on this. 

I've actually tried using a single global mock for all my tests and tested my tests for data race conditions and found none, so apparently there are no problems, but I don't want to find any in the future...

**Comment by l3pp4rd** [comment]
Hi, I would not suggest to use a global, you may instead create a few helper functions to simplify the boilerplate. global sqlmock instance may be safe concurrently, but you will not have an ordered expectation matching, which probably is important to write good tests. are you using `T.Parallel()` in your start of tests? if not then you may not notice the parallelization in test runs

**Comment by JairoBayonet** [comment]
No, I'm not using `T.Parallel()` in my tests, and you're right about the un-ordered expectation matching, sometimes it gets hard to know which test was the one that failed because of wrong expectations check up. Thanks for the prompt answer :)

**Comment by JairoGLoz** [comment]
No, I'm not using T.Parallel() in my tests, and you're right about the un-ordered expectation matching, sometimes it gets hard to know which test was the one that failed because of wrong expectations check up. Thanks for the prompt answer :)
