### ISSUE TITLE
Deadlock when not calling rows.Close() correctly.

### ISSUE THREAD

**Issue by Drahflow** [DATA-DOG/go-sqlmock#186]
Please find example code here:
https://gist.github.com/Drahflow/87ec588fe3d43af3db32bb20ad2279c6

**Comment by l3pp4rd** [comment]
I think the same deadlock will happen with any sql driver, there might be a connection blocked on the rows, while they are not being closed before calling next statement query. Sqlmock is a standard driver implementation and the issue most likely comes from the go sql implementation. Have you actually tried to use real db connection like mysql or psql?

**Comment by Drahflow** [comment]
You're right, I've reopened it as https://github.com/golang/go/issues/33938.
