### ISSUE TITLE
sqlmock failing with sql update

### ISSUE THREAD

**Issue by maha0894** [DATA-DOG/go-sqlmock#188]
We've been using sqlmock testing func() that are using select - no problems there.

It's not working with updates... The func we want to test is:

```
func PutTag(tag *Tag) error {
....
	err = db.DB.Where("id=?", tag.Id).Save(tag).Error
...
}
```

We've defined the test func like this:
```
func (s *Suite) TestPutTag() {
	tag := Tag{Id: 2, Name: "Test Tag 2"}
	s.mock.ExpectBegin()
	s.mock.ExpectPrepare("UPDATE `tags` SET `name` = ?  WHERE `tags`.`id` = ? AND ((id=?))").ExpectExec().
		WithArgs(tag.Name, tag.Id) // status, id
	s.mock.ExpectCommit()
	err := PutTag(&tag)
	require.NoError(s.T(), err)
}
```

This is returning..
[2019-08-30 11:08:14]  call to ExecQuery 'UPDATE `tags` SET `name` = ?  WHERE `tags`.`id` = ? AND ((id=?))' with args [{Name: Ordinal:1 Value:Test Tag 2} {Name: Ordinal:2 Value:2} {Name: Ordinal:3 Value:2}], was not expected, next expectation is: ExpectedPrepare => expecting Prepare statement which:
  matches sql: 'UPDATE `tags` SET `name` = ?  WHERE `tags`.`id` = ? AND ((id=?))'

The sql statements seem the same to me.. any ideas?

**Comment by l3pp4rd** [comment]
Hi, it seems like your `Save(tag) method does nor prepare the statement, it runs Exec directly, so you do not need to expect the prepare at all, just exec. Note, that sqlmock basic functionality works as expected and loads of users are using it daily, it is hardly possible that there will be a bug here in sqlmock library.

**Comment by maha0894** [comment]
Yep, you are right, my fault, got confused, while trying to make it work and trying different things...

```
func (s *Suite) TestPutTag() {
    tag := Tag{Id: 2, Name: "Test Tag 2"}
    s.mock.ExpectBegin()
    s.mock.ExpectQuery("UPDATE `tags` SET `name` = ?  WHERE `tags`.`id` = ? AND ((id=?))").
        WithArgs(tag.Name, tag.Id, tag.Id)
    s.mock.ExpectCommit()
    err := PutTag(&tag)
    require.NoError(s.T(), err)
}
```

But it still gives an error, as far as i understood because of the arguments, are they suppose to be some particular kind of struct?

Output: 

```
[2019-08-30 14:36:36]  call to ExecQuery 'UPDATE `tags` SET `name` = ?  WHERE `tags`.`id` = ? AND ((id=?))' with args [{Name: Ordinal:1 Value:Test Tag 2} {Name: Ordinal:2 Value:2} {Name: Ordinal:3 Value:2}], was not expected, next expectation is: ExpectedQuery => expecting Query, QueryContext or QueryRow which:
  - matches sql: 'UPDATE `tags` SET `name` = ?  WHERE `tags`.`id` = ? AND ((id=?))'
  - is with arguments:
    0 - Test Tag 2
    1 - 2
    2 - 2
```

**Comment by l3pp4rd** [comment]
Sql query is by default a regular expression, unless you specify it as a string matcher with options when initializing sqlmock. If you’d use just an **UPDATE** word instead of full query string, it should be matched. I suggest to use just patterns of sql statements for matching.

**Comment by mklef121** [comment]
> Yep, you are right, @l3pp4rd, my fault, got confused, while trying to make it work and trying different things...
> 
> ```
> func (s *Suite) TestPutTag() {
>     tag := Tag{Id: 2, Name: "Test Tag 2"}
>     s.mock.ExpectBegin()
>     s.mock.ExpectQuery("UPDATE `tags` SET `name` = ?  WHERE `tags`.`id` = ? AND ((id=?))").
>         WithArgs(tag.Name, tag.Id, tag.Id)
>     s.mock.ExpectCommit()
>     err := PutTag(&tag)
>     require.NoError(s.T(), err)
> }
> ```
> 
> But it still gives an error, as far as i understood because of the arguments, are they suppose to be some particular kind of struct?
> 
> Output:
> 
> ```
> [2019-08-30 14:36:36]  call to ExecQuery 'UPDATE `tags` SET `name` = ?  WHERE `tags`.`id` = ? AND ((id=?))' with args [{Name: Ordinal:1 Value:Test Tag 2} {Name: Ordinal:2 Value:2} {Name: Ordinal:3 Value:2}], was not expected, next expectation is: ExpectedQuery => expecting Query, QueryContext or QueryRow which:
>   - matches sql: 'UPDATE `tags` SET `name` = ?  WHERE `tags`.`id` = ? AND ((id=?))'
>   - is with arguments:
>     0 - Test Tag 2
>     1 - 2
>     2 - 2
> ```

Hello @maha0894  I ran into same issue, I realised gorm does execute the update statement, thus 

`sqlMocker.ExpectExec(regexp.QuoteMeta(`UPDATE "tags"`)).WillReturnResult(sqlmock.NewResult(1, 1))`

should work
