### ISSUE TITLE
Mock DB Connection Question

### ISSUE THREAD

**Issue by ahummel25** [DATA-DOG/go-sqlmock#191]
I have a query function that gets called and it fetches the DB connection, the DB connection is not passed in. This function gets called from several places and is basically a utility. Mocking the DB has been challenging because my function gets the actual connection every time. Is there any way to mock around this?

Utility function:

```
func RunQuery(query string, args []interface{}) *sql.Rows {
	sql := connection() // Gets the real connection, unable to mock
	defer sql.Close()

	results, err := sql.Query(query, args...)

	if err != nil {
	    log.Fatal(err)
	}

	return results
}
```

Connection func:

```
func connection() (db *sql.DB) {
	dbDriver := "mysql"
	dbHost := "HOST"
	dbPort := "PORT"
	dbUser := "USER"
	dbPass := "PASSWORD"
	dbName := "mydbname"
	db, err := sql.Open(dbDriver, dbUser+":"+dbPass+"@tcp"+"("+dbHost+":"+dbPort+")"+"/"+dbName)
	if err != nil {
	    log.Fatal(err)
	}
	return db
}
```

**Comment by l3pp4rd** [comment]
Hi, do you understand that this way you are using your database, opens a connection every time you call this method? Anyway, you can mock it only when passing around the sql.DB instance. That is usually the best approach. You can find out why on your own

**Comment by ahummel25** [comment]
@l3pp4rd I do understand that, but this particular API gets called from an AWS lambda, so each call to the API would be a new instance of the lambda and, therefore, a new DB connection.

**Comment by l3pp4rd** [comment]
hm, interesting case, but I guess the only workaround would be to wrap it in another function for testing
