### ISSUE TITLE
How can I use go-sqlmock to test a create table with specific primary key?

### ISSUE THREAD

**Issue by ahdong2007** [DATA-DOG/go-sqlmock#203]
I have a function to get the primary key columns from a table.
How can I use go-sqlmock to create a test case for this function?

Thansk in advance!

`type Mvl2Json struct {
	sync.Mutex
	db         *sql.DB
	schemaName string
	tableName  string
	mvlName    string
	logger     *logrus.Logger
	primaryKey []string
	lobColunms []string
	currentSeq int64 // 当前处理到的sequence$$
}

// primaryKey, 查询对象的主键列
func (m *Mvl2Json) PrimaryKey() {

	...
	m.primaryKey = append(m.primaryKey, primaryKeyColunm)
}`

**Comment by diegommm** [comment]
Hi @ahdong2007! Closing as there is not enough information to help you, unfortunately. If the problem persists, reopen and provide the following information:

- Your `sqlmock` version.
- What have you tried so far?
- Example code working on the Go Playground. Example: https://go.dev/play/p/CKPijIE9iYe.
- If you use any wrapping libraries (like gorm, sqlx, etc.), their names and version.

Thank you!
