### ISSUE TITLE
parallel testing

### ISSUE THREAD

**Issue by marcelloh** [DATA-DOG/go-sqlmock#206]
It's raining expectation errors, so my question is:
Is the mocking capable of handling concurrent (parallel) tests?

**Comment by l3pp4rd** [comment]
Hi, if you use the same db connection in separate go routines. Set the unordered matching option. You may also create separate db instances for each parallel coroutine if that is possible

**Comment by marcelloh** [comment]
I think, the New option gives me a new connection from the pool each time.
(when I printed dsn, I saw that)

I think you mean to set this:
mock.MatchExpectationsInOrder(false)

which I've tried, without success

**Comment by l3pp4rd** [comment]
It should be fine, maybe you are doing something wrong, if it invokes same query x times you have to expect it x times

**Comment by marcelloh** [comment]
I fixed it by changing the order of the commands :-)
