### ISSUE TITLE
go.mod pins to 1.12?

### ISSUE THREAD

**Issue by gliptak** [DATA-DOG/go-sqlmock#214]
https://github.com/DATA-DOG/go-sqlmock/blob/master/go.mod#L3

https://travis-ci.org/aws/aws-xray-sdk-go/jobs/640575466#L274

```
go build github.com/DATA-DOG/go-sqlmock: module requires Go 1.12
```

Is ```1.12``` the only targeted version?

**Comment by l3pp4rd** [comment]
No, got there by accident I guess

**Comment by gliptak** [comment]
@l3pp4rd will you offer a maintenance release?

**Comment by l3pp4rd** [comment]
done :)

**Comment by dolmen** [comment]
@gliptak I wonder about your issue with the "go 1.12" line.
Do you still use a Go version below 1.12 in production?
Can you tell us why?

**Comment by gliptak** [comment]
Your library project is used by other projects advertising older ```Go``` versions as supported (as linked above)

https://github.com/aws/aws-xray-sdk-go/blob/master/.travis.yml

Their builds started failing with the introduction of the ```1.12``` lower bound.
