### ISSUE TITLE
How to simulate the method of passing in *Sql.Tx parameters

### ISSUE THREAD

**Issue by jmuwfq** [DATA-DOG/go-sqlmock#232]
Like this:
```go
func (userDao *UserDao) UpdateByTx(tx *sql.Tx, user *User) (id int32, err error) {
	tx.Exec(....)
}
```

How to simulate tx.Exec(), I tried many times but failed

**Comment by diegommm** [comment]
Hi @jmuwfq! Closing as there is not enough information to help you, unfortunately. If the problem persists, reopen and provide the following information:

- Your `sqlmock` version.
- Example code working on the Go Playground. Example: https://go.dev/play/p/CKPijIE9iYe.
- If you use any wrapping libraries (like gorm, sqlx, etc.), their names and version.

Thank you!
