### ISSUE TITLE
WillReturnCloseError doesn't seem to work

### ISSUE THREAD

**Issue by iangudger** [DATA-DOG/go-sqlmock#25]
When I set WillReturnCloseError on ExpectPrepare, the driver.Stmt returned for the associated Prepare doesn't return an error when I try to close it.

See example code here:
https://github.com/iangudger/sqlmock_prepare_example/blob/master/main.go

**Comment by iangudger** [comment]
This issue should be resolved when https://github.com/golang/go/issues/12798 is resolved (currently scheduled for Go 1.6).

**Comment by l3pp4rd** [comment]
thanks @iangudger for looking it up. I will leave the issue open for others to notice.
