### ISSUE TITLE
Unexpected behavior matching multiple identical calls

### ISSUE THREAD

**Issue by paulturner-resolute** [DATA-DOG/go-sqlmock#253]
```
				db, mock, err := sqlmock.New()
				is.NoErr(err)
				rowSet := sqlmock.
					NewRows([]string{"col1", "col2", "col3"}).
					AddRow("expected", "result", "set")
				mock.ExpectQuery(selectSQL).
					WithArgs("1").
					WillReturnRows(rowSet).
					WillReturnError(errors.New("some error"))
```

I expected this to return my result set the first time it is called and then return the error the second and subsequent times it is called (like `Mockito` does), but it just returns the error consistently.  Is setting expectations like that possible?

**Comment by diegommm** [comment]
Hi @paulturner-resolute! Closing as there is not enough information to help you, unfortunately. If the problem persists, reopen and provide the following information:

- Your `sqlmock` version.
- Example code working on the Go Playground. Example: https://go.dev/play/p/CKPijIE9iYe.
- If you use any wrapping libraries (like gorm, sqlx, etc.), their names and version.

Thank you!
