### ISSUE TITLE
Match a multi argument query against an expectation with an unique argument(s)

### ISSUE THREAD

**Issue by nicwest** [DATA-DOG/go-sqlmock#26]
I'm hitting an issue where I want to mock a query but I don't know about (or in my particular case; don't care about) some of the arguments that the query was made with. I Also don't know what order the queries are made in

consider this somewhat convoluted example:

https://gist.github.com/nicwest/f902199d47f5c4a7902a

I would like to do something along the lines of

```go
	mock.ExpectQuery("SELECT word FROM things").WithUniqueArgs("Fred").WillReturnRows(
		sqlmock.NewRows(columns).AddRow("Fish"),
	)

	mock.ExpectQuery("SELECT word FROM things").WithUniqueArgs("Bat").WillReturnRows(
		sqlmock.NewRows(columns).AddRow("Bat"),
	)

	mock.ExpectQuery("SELECT word FROM things").WithUniqueArgs("Harry").WillReturnRows(
		sqlmock.NewRows(columns).AddRow("Horse"),
	)
```

Any suggestions?

**Comment by l3pp4rd** [comment]
Hi, there is an [example](https://github.com/DATA-DOG/go-sqlmock/blob/master/sqlmock_test.go#L621) with unordered matching. I think that will manage your use case.

**Comment by nicwest** [comment]
Thanks!

That I think solves part of my problem, the other bit is how I differentiate between two queries without specifying all of the arguments?

**Comment by l3pp4rd** [comment]
You may catch it by regular expression on SQL without providing any argument, in that case you need to know how many of these queries will be run and just add expectations in a loop only on SQL statement. If you provide at least one argument, only in that case arguments are being matched. Nothing prevents you from expecting SQL query like: `SELECT (.*) FROM things` or `^INSERT INTO things`

**Comment by nicwest** [comment]
Sure, but in the case that my query is `SELECT * FROM things WHERE thing=? AND foobar=?` and I know what `thing` will be but not `foobar`? I can think of some examples even under test conditions of where this could happen, for example a random number, a relation id, the current time, the process id, an OS specific file path, etc.

**Comment by l3pp4rd** [comment]
Ah, in that case you should use custom [argument matcher](https://godoc.org/github.com/DATA-DOG/go-sqlmock#Argument) for one which differs and you do not care about.
