### ISSUE TITLE
String 

### ISSUE THREAD

**Issue by afzalabbasi** [DATA-DOG/go-sqlmock#265]
Is there any way compare any string like anytime in go-sqlmock

**Comment by dolmen** [comment]
What about `==`?

**Comment by diegommm** [comment]
Hi @afzalabbasi! Closing as there is not enough information to help you, unfortunately. If the problem persists, reopen and provide the following information:

- Your `sqlmock` version.
- Example code working on the Go Playground. Example: https://go.dev/play/p/CKPijIE9iYe (thanks @fatelei!).
- If you use any wrapping libraries (like gorm, sqlx, etc.), their names and version.

Thank you!
