### ISSUE TITLE
Testing lib/pq with RETURNING clause.

### ISSUE THREAD

**Issue by nubunto** [DATA-DOG/go-sqlmock#27]
This is probably something silly, but I could't find a similar problem.

I have a query that must return the inserted `id`:

    INSERT INTO AuctionUser (name, coins) VALUES ($1, $2) RETURNING id;

I'm using `lib/pq`, and it [doesn't support the LastInsertId method](https://github.com/lib/pq/issues/24).

Anyway, my test is failing at the point on which I decide the returning rows:

    mock.ExpectQuery("INSERT INTO AuctionUser (.+) RETURNING id").
        WithArgs(mockUser.Name, mockUser.Coins).
        WillReturnRows(sqlmock.NewRows([]string{"id"}))

It says that it has `no rows on result set`.
Am I missing something?

**Comment by l3pp4rd** [comment]
Hi, you need to build a result set yourself in test case:

``` go
mock.ExpectQuery("INSERT INTO AuctionUser (.+) RETURNING id").
    WithArgs(mockUser.Name, mockUser.Coins).
    WillReturnRows(sqlmock.NewRows([]string{"id"}).AddRow(5))
```

In that case, there will be 1 row with column **id** and value **5** for that column

**Comment by l3pp4rd** [comment]
You can also visit [test cases](https://github.com/DATA-DOG/go-sqlmock/blob/master/sqlmock_test.go) to quickly find an example you may need..

**Comment by nubunto** [comment]
Oh, I see. I'll take a look at the test cases. Thank you for your time!
