### ISSUE TITLE
How to get the mock connection url string from *sql.DB for unit testing PostgreSQL queries

### ISSUE THREAD

**Issue by Dmaddu** [DATA-DOG/go-sqlmock#273]
Hello there,

I have a function that accepts Postgres connection URL, instead of *sql.DB.
With  `db, mock, err := sqlmock.New()` I am getting db of type *sql.DB

Is there any way to get the connection URL from *sql.DB so that I can mock the queries that trigger in my function.  

my method looks like as below 

func MyFunc(dbconn string){
 ...
}

**Comment by dolmen** [comment]
Try [NewWithDSN](https://pkg.go.dev/github.com/DATA-DOG/go-sqlmock#NewWithDSN).

**Comment by Ghvstcode** [comment]
Hi, It seems @dolmen answered your question & this thread has been inactive for a while so I will be closing this.
