### ISSUE TITLE
Access to underlying driver.Driver?

### ISSUE THREAD

**Issue by slnt** [DATA-DOG/go-sqlmock#276]
I am using the package [sqlmw](github.com/ngrok/sqlmw) to write an interceptor that adds logging and tracing to an arbitrary underlying driver. I'd like to test this with `sqlmock` but am running into a roadblock due to the fact that the `sqlmw.Driver` functions requires a `driver.Driver`. The driver that is implemented in `sqlmock`, however, is unexported, making the use of the library rather tricky... I'm not sure about what the RightWay™ might be to expose the underlying driver implementation that Sqlmock uses, especially such that it is openable by `sql.Open`.

**Comment by dolmen** [comment]
You can get access to the driver via `db.Driver()`.

[Example on the Go Playground](https://go.dev/play/p/CqtfHpCZTBO):

```go
	db, _, err := sqlmock.New()
	drv := db.Driver()
```

**Comment by Ghvstcode** [comment]
Hi, It seems @dolmen answered your question & this thread has been inactive for a while so I will be closing this.
