### ISSUE TITLE
Is json tag is not used in this tool

### ISSUE THREAD

**Issue by sevenguin** [DATA-DOG/go-sqlmock#281]
`
type Temp struct {
        SourceType string `json:"SourceKind"`
}
`
when i mock like this:
`
mockRows := sqlmock.NewRows([]string{"source_kind"})
`
it's unusefule, bug when i mock like this:
`
mockRows := sqlmock.NewRows([]string{"source_type"})
`
it's ok.

**Comment by fatelei** [comment]
Please post some example code working on the Go Playground. Here is [a template](https://go.dev/play/p/CKPijIE9iYe).

**Comment by diegommm** [comment]
Hi @sevenguin! Closing as there is not enough information, unfortunately. If the problem persists, try providing:

- Your `sqlmock` version
- Example code working on the Go Playground (linking the same as @fatelei povided, which is great: https://go.dev/play/p/CKPijIE9iYe).
- If you use any wrapping libraries (like gorm, sqlx, etc.), their names and version

Thank you!
