### ISSUE TITLE
Getting 'Query: could not match actual sql' on identical queries

### ISSUE THREAD

**Issue by z4id** [DATA-DOG/go-sqlmock#303]
### Operating system and Go Version
- OS: macOS Ventura 13.0 (22A380)
- System: Macbook Apple M1 Air
- go version: go1.16.15 darwin/arm64 (Tried with go1.18.2 darwin/arm64 & go1.19 darwin/arm64 as well)
- go-sqlmock: v1.5.0

### Issue
Getting error "Query: could not match actual sql" even though both strings are identical. (compared via another tool)
```go
rows, err := d.DB.Query(query)
```
**P.S:**: Same code is working on other systems. Not sure whether its related to different hardware architecture or OS.

### Reproduction steps
SQL query is mocked like this:
```go
mock.ExpectQuery(regexp.QuoteMeta(expectedQuery)).WillReturnRows(rows)
```
#### Expected Result
There should be no error.

#### Actual Result
 > Query: could not match actual sql:

**Comment by thecodecafe** [comment]
Hey @z4id were you able to figure this issue out? Experiencing this as well.

**Comment by thecodecafe** [comment]
@z4id found a solution [here](https://github.com/DATA-DOG/go-sqlmock/issues/268#issuecomment-1426906227) in another issue.
