### ISSUE TITLE
Issue with JSON Byte matching

### ISSUE THREAD

**Issue by nishgop** [DATA-DOG/go-sqlmock#317]
### Operating system and Go Version
Mac OS Ventura 13.4

### Issue
Json Byte does not consistently match for every run

### Reproduction steps
TBD

#### Expected Result
Always matches consistently

#### Actual Result
It does not always match JSON Bytes and throws the above error complaining that it does not match when in fact the contents are identical

**Comment by diegommm** [comment]
Hi @nishgop! Please, consider reopening if you still experience this issue, but first make sure to provide more information:

- What version of `sqlmock` you are using.
- Example working code snippet to reproduce the issue.
- If you're using a wrapper library, its name and version as well.

Thank you!
