### ISSUE TITLE
go get path

### ISSUE THREAD

**Issue by jingles** [DATA-DOG/go-sqlmock#34]
Seems like the install instructions need to be updated:

go get github.com/DATA-DOG/go-sqlmock

**Comment by l3pp4rd** [comment]
not necessary, gopkg.in is used to get at specific version based on major release version tag. I think it is proper to use this package url in case if you want to be sure it will not get backward incompatible. you may also use a direct package path from github if you always want it at HEAD of master branch..

**Comment by jingles** [comment]
ok, I see.

it doesn't match the import path in the examples in the README, so this could be noted in one place or the other in the README...

Thanks
