### ISSUE TITLE
argMatches doesn't handle []byte properly

### ISSUE THREAD

**Issue by skriptble** [DATA-DOG/go-sqlmock#35]
Line 352 of expectations.go causes a panic when the driver.Value is a slice of bytes because it is an uncomparable type:

`panic: runtime error: comparing uncomparable type []uint8`

This panic isn't recovered because it is called directly from sqlmock.Exec. A solution would be to use reflect.DeepEqual instead of using a != check. Another would be to check if either the dargs or the args[k] are slices of bytes and then user bytes.Equal, if not then default to the != check.

**Comment by l3pp4rd** [comment]
hi @skriptble could you submit a pull request? it seems to be important
