### ISSUE TITLE
Is there any way to mock a sql.Rows object?

### ISSUE THREAD

**Issue by xiezhenye** [DATA-DOG/go-sqlmock#42]
Is there any way to mock a sql.Rows object?
sqlmock.Rows can not be used as sql.Rows

**Comment by dimiro1** [comment]
@xiezhenye take a look [1] I think it is what you need.

[1] https://github.com/DATA-DOG/go-sqlmock/blob/master/examples/blog/blog_test.go#L41-L45

**Comment by l3pp4rd** [comment]
thanks for the help @dimiro1 
does that answer your question @xiezhenye ? sqlmock can simulate whole **sql** package behavior and act exactly as you mock it to act.

**Comment by xiezhenye** [comment]
Thanks，I've tried this:

    func mockRowsToSqlRows(mockRows sqlmock.Rows) *sql.Rows {
        db, mock, _ := sqlmock.New()
        mock.ExpectQuery("select").WillReturnRows(mockRows)
        rows, _ := db.Query("select")
        return rows
    }

**Comment by l3pp4rd** [comment]
I think you are misusing the library @xiezhenye you are not supposed to convert these, your testable code should execute db.Query as usually it would be and get the rows mocked with sqlmock in a test case.

**Comment by stormsc1** [comment]
> I think you are misusing the library [@xiezhenye](https://github.com/xiezhenye) you are not supposed to convert these, your testable code should execute db.Query as usually it would be and get the rows mocked with sqlmock in a test case.

I know this is an old issue, but I am still not satisfied with the solution proposed. I am testing the scanning part of my database adapter. I just want to construct rows directly for scanning without a whole bunch of boilerplate. Is there still no good way to do this, and why?

Something like this:
```go
	rows := sqlmock.NewActualRows([]string{"uuid", "created_at", "updated_at", "deleted_at"}).
		AddRow("123e4567-e89b-12d3-a456-426614174000", "2021-01-01T00:00:00Z", "2021-01-01T00:00:00Z", nil).
		AddRow("123e4567-e89b-12d3-a456-426614174001", "2021-01-01T00:00:00Z", "2021-01-01T00:00:00Z", nil)

```
