### ISSUE TITLE
ExpectQuery putting mock select statement inside brackets

### ISSUE THREAD

**Issue by briemarie** [DATA-DOG/go-sqlmock#44]
I have the following select statement in a GetLinks function: 

`r.DB.Query("SELECT * FROM links ORDER BY short_url ASC")`

And am testing it as follows: 

```
func GetLinksTest(mock sqlmock.Sqlmock, r *repo.Repo, t *testing.T, err error) {
	mock.ExpectQuery("SELECT * FROM links ORDER BY short_url ASC").WillReturnRows(link_rows)

	if _, err = r.GetLinks(); err != nil {
		t.Errorf("error was not expected while selecting from links: %s", err)
	}
}
```

The error that is returned is:
`error was not expected while selecting from links: query 'SELECT * FROM links ORDER BY short_url ASC', does not match regex [SELECT * FROM links ORDER BY short_url ASC]`

*Note the brackets added around the mock select statement

The most peculiar part of the whole thing is that if I add brackets to my original select statement, they still do not match. 

`r.DB.Query("[SELECT * FROM links ORDER BY short_url ASC]")`

returns

`error was not expected while selecting from links: query '[SELECT * FROM links ORDER BY short_url ASC]', does not match regex [SELECT * FROM links ORDER BY short_url ASC]`

BUT, if I add brackets to the mock query and not the original query, the test passes!

```
row, err := r.DB.Query("SELECT * FROM links ORDER BY short_url ASC")
mock.ExpectQuery("[SELECT * FROM links ORDER BY short_url ASC]").WillReturnRows(link_rows)
```
How is it that brackets are being added to the mock query, and then magically being taken away by adding brackets?

**Comment by briemarie** [comment]
I am now also getting this error on another test: 

`error was not expected while selecting from links: exec query 'UPDATE links SET name=$1, notes=$2 WHERE id=$3', does not match regex 'UPDATE links SET name=$1, notes=$2 WHERE id=$3'`

*Note that the two queries are exactly the same.

BUT, once again, adding brackets around the ExpectExec update statement makes the test pass.

**Comment by l3pp4rd** [comment]
All queries translate to regular expressions. so you have to escape the special symbols. Look through examples. you usually do not need to match exact query. it is enough to expect `SELECT (.+) FROM links` as an example.

**Comment by estarner-sugarcrm** [comment]
@briemarie did you ever find an actual solution to this? The answer given doesnt address the problem and I am experiencing this same issue.
