### ISSUE TITLE
Results: A query should be allowed to return 0 rows

### ISSUE THREAD

**Issue by huttotw** [DATA-DOG/go-sqlmock#45]
For instance, maybe you are trying to find a user based on their email address, if the query comes back with 0 rows in real life, you know that the user doesn't exist. There should be a way to return 0 rows without throwing an error.

**Comment by l3pp4rd** [comment]
can't you currently do it?

``` go
rs := NewRows([]string{"id", "name"})

mock.ExpectQuery("SELECT (.+) FROM users WHERE id = ?").
	WithArgs(5).
	WillReturnRows(rs)
```
