### ISSUE TITLE
Impossible to mock errors return from rows.Scan()

### ISSUE THREAD

**Issue by johanbrandhorst** [DATA-DOG/go-sqlmock#47]
Hi,

I've been using a lot of go-sqlmock and I'm really liking it. However, there doesn't seem to be way to mock the error returned from rows.Scan() when called on an object returned from database.Query (a rows object). There is an example of how to use RowError to check the error returned from rows.Err(), but this is not the same as the error returned from rows.Scan().

Here I've extended the RowError example from godoc to illustrate my issue:

```go
db, mock, err := New()
if err != nil {
    fmt.Println("failed to open sqlmock database:", err)
}
defer db.Close()

rows := NewRows([]string{"id", "title"}).
    AddRow(0, "one").
    AddRow(1, "two").
    RowError(1, fmt.Errorf("row error"))
mock.ExpectQuery("SELECT").WillReturnRows(rows)

rs, _ := db.Query("SELECT")
defer rs.Close()

for rs.Next() {
    var id int
    var title string
    // -------------------------------------------------
    // How do we mock this error?
    err := rs.Scan(&id, &title)
    if err != nil {
        fmt.Println("got scan error:", err)
        break
    }
    // -------------------------------------------------
    fmt.Println("scanned id:", id, "and title:", title)
}

if rs.Err() != nil {
    fmt.Println("got rows error:", rs.Err())
}
```

**Comment by l3pp4rd** [comment]
Hi, good to hear that you like the library. Scan error is only related to value transformation.

For example if you change your code to:

``` go
db, mock, err := New()
if err != nil {
    fmt.Println("failed to open sqlmock database:", err)
}
defer db.Close()

var notString = 1

rows := NewRows([]string{"id", "title"}).
    AddRow(-1, "one").
    AddRow(1, notString).
    RowError(1, fmt.Errorf("row error"))
mock.ExpectQuery("SELECT").WillReturnRows(rows)

rs, _ := db.Query("SELECT")
defer rs.Close()

for rs.Next() {
    var id uint
    var title string
    // -------------------------------------------------
    // How do we mock this error?
    err := rs.Scan(&id, &title)
    if err != nil {
        fmt.Println("got scan error:", err)
        break
    }
    // -------------------------------------------------
    fmt.Println("scanned id:", id, "and title:", title)
}

if rs.Err() != nil {
    fmt.Println("got rows error:", rs.Err())
}
```

It should fail with scan error. because the first and second rows cannot be scanned due to their types

**Comment by johanbrandhorst** [comment]
Aha! You are indeed right. Thanks for the help. May I suggest adding something to this effect to the godoc documentation?

**Comment by l3pp4rd** [comment]
yes sure ;) may be helpful

**Comment by l3pp4rd** [comment]
maybe you want to contribute this one?

**Comment by Agronis** [comment]
Unless I am just completely overlooking something, the following behavior is unintended and likely should be opened as a bug?  I am hopping on this thread first as to not cause unnecessary noise, so please confirm if you agree.  However, I do understand the other side of the coin that is to say, I am able to take these value types from SQL and convert to string without explicitly asking to do so.

If the values you are attempting to read into are designated as strings, the only viable format you may pass `RowError` is `nil`.  Use of any other data type either casts (bool, int, float, etc) into a string format, or will cause a panic (struct{}{}, func(){}, []slice, map[]...)

At the very least, this edge case perhaps should be documented along side `RowError` as `If attempting to trigger a scan err against string data types, you must pass nil`

Example:

```
	var (
		var1 string
		var2 sql.NullString
	)
	for rows.Next() {
		err := rows.Scan(&var1, &var2)
		if err != nil {
			return nil, err
		}
        }
```

```
... someTest()
		rows := sqlmock.NewRows([]string{"var1", "var2"})
		rows.AddRow("foo","bar")
		// any use of an integer, float, bool will not satisfy this eg:
		// rows.AddRow(false, "foo")
		// as they will simply be cast into a string value
		// if you attempt to use func(){}, struct(){} or a slice/map
		// panic()
		// your only option is nil
		rows.AddRow(nil, "foobar").RowError(2, errors.New("scanErr")

		mock.ExpectQuery("SELECT").WillReturnRows(rows)

		_, err := someFunc()

		assert.Error(t, err)

```

**Comment by kartheekDogga** [comment]
one can try data type mismatch, for string i could think of passing nil to create a row Scan error `row := mock.NewRows([]string{"column"}).AddRow(nil)`

**Comment by jfelipends** [comment]
I'm having this issue but I think my case is a little harder, my code uses `sql.RawBytes`, and I didn't realized how could I make it fails so `Scan` returns an error.

We do:
```go
	values := make([]sql.RawBytes, len(cols))

	scanArgs := make([]interface{}, len(values))
	for i := range values {
		scanArgs[i] = &values[i]
	}

	for rows.Next() {
		err = rows.Scan(scanArgs...)
		if err != nil {
			logger.Error("Error scanning: " + err.Error())
			continue
		}
...
```

And the test:

```go
queryRows := sqlmock.NewRows(entity.attributes) // six attributes of type sql.driver.Value
queryRows.AddRow(-1, "1", "10", "10", "P", nil)

if tt.wantErrScan {
    queryRows.RowError(0, errors.New("forced error"))
}
```
It doesn't even calls Scan, because Next returns false. I did tried to mock many kinds of values, none seem to work. Any help?
