### ISSUE TITLE
ExpectePrepare does not work as documented 

### ISSUE THREAD

**Issue by luistm** [DATA-DOG/go-sqlmock#50]
Hi everyone!
First, thanks for the excellent work with sqlmock. 

I'm writing some test code with the help of go sqlmock. 

The following code does not validates if the prepared statement has the correct query. 

```
// main.go
package main

import "database/sql"

func testFunction(db *sql.DB) {
	db.Prepare("SELECT")
}

func main() {}
```

```
// main_test.go
package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
	sqlmock "gopkg.in/DATA-DOG/go-sqlmock.v1"
)

func TestPrepare(t *testing.T) {
	db, mock, mErr := sqlmock.New()
	assert.NoError(t, mErr)
	defer db.Close()

	mock.ExpectPrepare("^BADSELECT$")

	testFunction(db)

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("there were unfulfilled expections: %s", err)
	}

}
```

As far as i know, the test **should fail,** but it does't. What i'm i doing wrong? 
I'm using GO 1.7/macOS 10.12.1. 

Thanks

**Comment by l3pp4rd** [comment]
Hi, yes indeed, for some reason it was not validating the sql query on prepare. looks like everyone was using that statement for Exec or Query and that was validating it.

**Comment by l3pp4rd** [comment]
thanks for reporting it ;)
