### ISSUE TITLE
Update to support new 1.8 go SQL features

### ISSUE THREAD

**Issue by l3pp4rd** [DATA-DOG/go-sqlmock#52]
see https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit

**Comment by derekperkins** [comment]
Are there any plans to add support for the new functionality?

**Comment by l3pp4rd** [comment]
yes there are, I'm thinking to resolve this in few weeks time, I'll have a look this week how much of the work it may involve. If it is few hour work, then it may be done this week, cheers
