### ISSUE TITLE
escaping subqueries and other chars

### ISSUE THREAD

**Issue by cryptix** [DATA-DOG/go-sqlmock#6]
Hi,

when I started adding tests for one of my db package I had the problem that my queries mostly all contained sub queries (and thus `(` and `)`) were spread across multiple lines or contained other regex-relevant characters which then were treated by the regex engine which then resulted in lots of `exec query 'rawQuery', does not match regex 'rawQuery'`

After escaping the first bunch by hand I hacked together this small helper:

``` go
// small testing helper to escape `(`, `)` and `$` to not be used as regex modifiers
func escapeQueryToRegex(in string) (out string) {
    // replace multiple spaces, tabs and newlines with one space
    out = strings.Join(strings.Fields(in), " ")

    // slice of regex relevant characters which need to be escaled
    chars := []string{`(`, `)`, `$`, `+`}
    for _, r := range chars {
        out = strings.Replace(out, r, `\`+r, -1)
    }

    return out
}
```

I wonder if there is a smarter solution for this problem and if not would have no problem with you guys including this in go-sqlmock. It's an awesome package. Thanks!

**Comment by thurt** [comment]
fyi for future readers: you may find [regexp.QuoteMeta](https://godoc.org/regexp#QuoteMeta) helpful. It will automatically escape special regexp characters. I use it a helper function inside relevant test file:

```golang
func esc(stmt string) string {
    return regexp.QuoteMeta(stmt)
}
```
