### ISSUE TITLE
Can `MatchExpectationsInOrder` be modified after some expectations have been already set?

### ISSUE THREAD

**Issue by AA33** [DATA-DOG/go-sqlmock#60]
How does this method affect expectation matching? There could be two ways it could work:
- Allow random order on all expectations set before or after calling this method.
- Allow random order on expectations set after calling this method while expectations set before calling this method are expected to be in order.

Which of the above (or some other logic) is the current functionality? The documentation seems to have skipped over this.

**Comment by l3pp4rd** [comment]
yes probably will need to document it in more detail. it is affected right after you set it.

- given you have a list of expectations, `MatchExpectationsInOrder` is **true**
- when execute few queries in expected order
- and you change `MatchExpectationsInOrder` to **false**
- the rest of unfulfilled expectations can be matched in any order
