### ISSUE TITLE
Asserting on no queries

### ISSUE THREAD

**Issue by orenmazor** [DATA-DOG/go-sqlmock#63]
I'm trying to add a test that expects no queries to occur. I imagined this would be simply creating a mock db and it would raise an error if an unexpected query of some kind happened. It looks like it does, but it doesn't fail the test.

```
all expectations were already fulfilled, call to query 'SELECT store_id, address, topic FROM webhook WHERE id=0 AND active=1 LIMIT 1;' with args [] was not expected
PASS
ok      github.com/foo     0.011s
```

I'm assuming this would be something that needs to go in here to compare the count? https://github.com/DATA-DOG/go-sqlmock/blob/d4cd2ca2ad1cc2130bba385aab072218f131f636/sqlmock.go#L146

**Comment by l3pp4rd** [comment]
sqlmock does not integrated with `testing.T` so all errors are returned by sql interface which integrates sqlmock driver. Maybe it is not usual and awkward at first. So if you have no expected queries and you call for example `err := sql.DB.QueryRow("SELECT 1").Scan(&myInt);` the error will not be empty. so either a panic or an error should be returned from a method executing this sql query.

The method you are referring to, does what it say, it checks if all expectations were met, you had none.

**Comment by l3pp4rd** [comment]
does it make sense?
