### ISSUE TITLE
Document breaking change to WillReturnRows

### ISSUE THREAD

**Issue by rapropos** [DATA-DOG/go-sqlmock#69]
I believe [this commit](https://github.com/DATA-DOG/go-sqlmock/commit/128bf5c539d9ca228e5ae3f2d02770c8ffb6dd91) changed the argument type of WillReturnRows from `Rows` to `*Rows`, which broke a lot of my existing test code. Perhaps a note in the README would help others in the same situation.

**Comment by l3pp4rd** [comment]
there is a note in change log. in order to support go 1.8 features it was changed to struct. what exactly was a breaking change for you? you have used some helper methods for Rows interface? If that is common among users I could look into ways to revert it back to interface

**Comment by rapropos** [comment]
> what exactly was a breaking change for you? you have used some helper methods for Rows interface?

Yes, I had many helper functions with roughly the following structure:

```
var mockFooCols = []string{"a", "b", "c"}

func mockFooRows(foos []Foo) sqlmock.Rows {
  rows := sqlmock.NewRows(mockFooCols);
  for _, foo := range foos {
    rows.AddRow(foo.A, foo.B, foo.C)
  }
  return rows
}
```

All of these had to be redefined to return `*sqlmock.Rows` instead. Initially, I had thought this was going to affect all rows objects created inline as well, forcing me to define a bunch of variables that I didn't really want just in order to take their address, but it seems that is not the case, so perhaps this isn't as big of a deal as I thought when I created the issue. In any event, thank you for your work on the library. It is very helpful.

**Comment by l3pp4rd** [comment]
Thanks, I will maintain backward compatibility as much as I can, I hate it the same way you do, when someone releases v2 or makes incompatible changes often. Guess everyone hates it :) I probably will never change public api of sqlmock, if I would it would be a different repository
