### ISSUE TITLE
Intermittent failure on mock.ExpectQuery("your regex").WillReturnRows(your_rows)

### ISSUE THREAD

**Issue by alexanderGalushka** [DATA-DOG/go-sqlmock#74]
I have a test that mocks 2 subsequent DB queries. After an upgrade to 1.8.1 Go version the second mock fails to return the data every other time. On 1.7.4_2 it was working consistently with no issues. 

Here are my 2 mocks:

```
		mock.ExpectQuery("^SELECT (.+) COALESCE(.+)$").WillReturnRows(rows)
		mock.ExpectQuery("^SELECT count(.+)$").WillReturnRows(rowsForTotal)
```

**Comment by l3pp4rd** [comment]
Hi what was the issue?
