### ISSUE TITLE
ExpectQuery used when ExpectExec is right produces confusing error. 

### ISSUE THREAD

**Issue by ajackson-cpi** [DATA-DOG/go-sqlmock#77]
After many ExpectQuery tests, I copy-pasted it for an exec. The error made it seem like the arguments were mismatched when in reality I needed ExpectExec. 

Please clean-up this error so that when the queries match that it indicates it should have been an Exec.

**Comment by l3pp4rd** [comment]
Hi, could you make a screenshot, because as far as I remember it mentions in the output about exact expectation type

**Comment by l3pp4rd** [comment]
![2017-04-26-091625](https://cloud.githubusercontent.com/assets/132389/25420509/0e0706b6-2a61-11e7-8fa3-2ae3dd883253.png)

well maybe it is a little confusing `call to exec query` might not be highly visible. But if I change it to `ExecQuery` there is also `ExecQueryContext` not sure whether that would be also confusing.
