### ISSUE TITLE
Allow expectations to be reused

### ISSUE THREAD

**Issue by mikemacd** [DATA-DOG/go-sqlmock#82]
I think it would be useful to allow the option of expectations to be reused by adding a flag similar to `MatchExpectationsInOrder` defaulting to false. When set it would add a bypass to the [`continue`](https://github.com/DATA-DOG/go-sqlmock/blob/master/sqlmock.go#L317) in the `if next.fulfilled() { ... }` blocks.

**Comment by l3pp4rd** [comment]
yes, might make sense for such an option like `AllowRepeatedExpectationMatching`. though, then it is ExpectedQuery, the Rows offset should be reset on each match. Would you care to implement it?

**Comment by mikemacd** [comment]
Sure, I'll look into implementing it this evening.

**Comment by mikemacd** [comment]
I don't see a way to be able to reset the rows offset in the driver Rows, so it would seem to me that this feature may not be achievable.

**Comment by l3pp4rd** [comment]
Since [driver.Rows](https://github.com/DATA-DOG/go-sqlmock/blob/master/expectations.go#L129) is an interface you can always cast it to type. And we are certain, if it is not `nil` that it will be [rowSets](https://github.com/DATA-DOG/go-sqlmock/blob/master/rows.go#L22)

So the code [on this block](https://github.com/DATA-DOG/go-sqlmock/blob/master/sqlmock.go#L441-L444) should be the following:

``` go
if expected.rows == nil {
	return nil, fmt.Errorf("Query '%s' with args %+v, must return a database/sql/driver.Rows, but it was not set for expectation %T as %+v", query, args, expected, expected)
}

// reset rows for next use if allowed
if rs, ok := expected.rows.(*rowSets); ok {
	rs.pos = 0
	for _, set := range rs.sets {
		set.pos = 0
	}
}

return expected, nil
```

Does it make sense?

**Comment by mikemacd** [comment]
I hadn't considered that approach. Thanks! I'll try using it.

**Comment by bernielomax** [comment]
I have been looking at this also. My idea was to be able to join mocks. My idea was to allow prepend or append (or just join) on the []expectations inside the sqlmock struct?

```
type sqlmock struct {
	ordered bool
	dsn     string
	opened  int
	drv     *mockDriver

	expected []expectation
}
```

**Comment by l3pp4rd** [comment]
see another better attempt #148 but after long thought, this may lead to inconsistencies in behavior. cannot accept that
