### ISSUE TITLE
Query matching problem

### ISSUE THREAD

**Issue by mauricioklein** [DATA-DOG/go-sqlmock#86]
Hello!

First of all, sorry for opening an issue for this problem, but I've tried different approaches and checked all the `example/`, but none seems to work.

I basically wanna mock the return of a query in my tests, but no matter the regex I use, it never matches.

```go
func TestGetProviderByName(t *testing.T) {
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("Could not mock the database connection: %s", err)
	}
	defer db.Close()

	rows := sqlmock.NewRows([]string{"id", "name", "searchable"}).
		AddRow(1, "Foobar", true)

	mock.ExpectQuery("SELECT (.+) FROM user WHERE name ILIKE \\$1$").WithArgs("Foobar").WillReturnRows(rows)

	db.Query(`
		SELECT id, name, searchable
		FROM user
		WHERE
			name ILIKE $1
	`, "Foobar")

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("There are unfulfilled expectation: %s", err)
	}
}
```

Even if I change the ExpectQuery statement for the one below, I still got an error about unfulfilled expectation:

```go
mock.ExpectQuery("SELECT id, name, searchable FROM user WHERE name ILIKE 'Foobar'").WillReturnRows(rows)
```

Am I doing something wrong?!

Thanks in advance for any help!

**Comment by l3pp4rd** [comment]
Hi, pull and checkout branch `issue-86` and run `go test github.com/DATA-DOG/go-sqlmock/examples/basic` the [test passes](https://github.com/DATA-DOG/go-sqlmock/blob/issue-86/examples/basic/basic_test.go#L60)

**Comment by mauricioklein** [comment]
Thanks @l3pp4rd 
Should be something in my setup, because now both `issue-86` and mine branch works.
Thanks for your support and sorry about that 👍

**Comment by l3pp4rd** [comment]
you are welcome, cheers
