### ISSUE TITLE
Check if Close gets called on a *sql.Stmt / Prepared Statement

### ISSUE THREAD

**Issue by SchumacherFM** [DATA-DOG/go-sqlmock#89]
Hi there and thanks for this great library!

Today I ran into one minor issue. I've created a prepared statement `*sql.Stmt` and wanted to check if I really call `sql.Stmt.Close` but there is no such check. 

An example picked from one of the issues here with the new feature:

```
func TestLogHistory(t *testing.T) {
	var mock sqlmock.Sqlmock
	var err error
	db, mock, err = sqlmock.New()
	if err != nil {
		t.Fatal(err)
	}

	mock.ExpectPrepare("INSERT INTO").
	ExpectExec().WithArgs("2").WillReturnResult(sqlmock.NewResult(1, 1)).
	ExpectClose() // <-- checks if the stmt gets closed.

	stmt, err := db.Prepare("INSERT INTO history VALUES(?)")
	if err != nil {
		panic(err)
	}
	defer stmt.Close() // <-- we call Close so all is fine.

	if _, err := stmt.Exec("2"); err != nil {
		t.Fatal(err)
	}

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Fatal(err)
	}
}
```
The `ExpectationsWereMet` function should report, that you forgot to call `sql.Stmt.Close`.
Also there should be a `WillExpectCloseWithError()` or similar.

What do you think? If it's not worth ... just close this issue.

**Comment by l3pp4rd** [comment]
Hi, thanks. I will have a look later and think about it. the most important aspect is to maintain backward compatibility and do not introduce more complexity in understanding the usage. I need some time to spend in order to answer that properly ;)

**Comment by l3pp4rd** [comment]
So far the best option for this, which I have thought is something like this:

``` go
func TestLogHistory(t *testing.T) {
	var mock sqlmock.Sqlmock
	var err error
	db, mock, err = sqlmock.New()
	if err != nil {
		t.Fatal(err)
	}

	mock.ExpectPrepare("INSERT INTO").
        WillBeClosed().
	ExpectExec().WithArgs("2").WillReturnResult(sqlmock.NewResult(1, 1))

        if err := doWork(db); err != nil {
               t.Fatal(err)
        }

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Fatal(err)
	}
}

func doWork(db *sql.DB) error {
        stmt, err := db.Prepare("INSERT INTO history VALUES(?)")
	if err != nil {
		return err
	}
	defer stmt.Close() // <-- we call Close so all is fine.

	if _, err := stmt.Exec("2"); err != nil {
		return err
	}
        return nil
}
```

In you example defer close would execute after `ExpectationsWereMet` check and ExpectClose would be called on an Exec expectation which is not a PrepareExpectation.
