### ISSUE TITLE
Package not usable with parallel tests

### ISSUE THREAD

**Issue by jnwhiteh** [DATA-DOG/go-sqlmock#9]
There is currently a data race when using go-sqlmock in two tests in parallel due to the way the API is currently designed. There is only ever one "mock" database and all operations are done on this. This means two tests cannot use this package in parallel. This is evidenced from the following data race in a package I am developing. I'm going to take a stab and changing the API to accommodate this.

    ==================
    WARNING: DATA RACE
    Read by goroutine 10:
      github.com/DATA-DOG/go-sqlmock.ExpectQuery()
          /Users/jnwhiteh/go/src/github.com/DATA-DOG/go-sqlmock/sqlmock.go:155 +0x138
      github.com/jnwhiteh/migration.setupVersioned()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:35 +0x22a
      github.com/jnwhiteh/migration.TestDowngradesUnsupported()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:61 +0x73
      testing.tRunner()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:422 +0x10f
    
    Previous write by goroutine 8:
      github.com/DATA-DOG/go-sqlmock.(*conn).Close()
          /Users/jnwhiteh/go/src/github.com/DATA-DOG/go-sqlmock/connection.go:24 +0x266
      database/sql.(*driverConn).finalClose()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:310 +0x175
      database/sql.finalCloser.(database/sql.finalClose)·fm()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:398 +0x57
      database/sql.(*DB).Close()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:487 +0x6fa
      github.com/jnwhiteh/migration.TestFailingToGetCurrentVersion()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:54 +0x331
      testing.tRunner()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:422 +0x10f
    
    Goroutine 10 (running) created at:
      testing.RunTests()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:504 +0xb46
      testing.Main()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:435 +0xa2
      main.main()
          github.com/jnwhiteh/migration/_test/_testmain.go:61 +0xdc
    
    Goroutine 8 (finished) created at:
      testing.RunTests()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:504 +0xb46
      testing.Main()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:435 +0xa2
      main.main()
          github.com/jnwhiteh/migration/_test/_testmain.go:61 +0xdc
    ==================
    ==================
    WARNING: DATA RACE
    Write by goroutine 10:
      github.com/DATA-DOG/go-sqlmock.ExpectQuery()
          /Users/jnwhiteh/go/src/github.com/DATA-DOG/go-sqlmock/sqlmock.go:156 +0x309
      github.com/jnwhiteh/migration.setupVersioned()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:35 +0x22a
      github.com/jnwhiteh/migration.TestDowngradesUnsupported()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:61 +0x73
      testing.tRunner()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:422 +0x10f
    
    Previous write by goroutine 8:
      github.com/DATA-DOG/go-sqlmock.(*conn).Close()
          /Users/jnwhiteh/go/src/github.com/DATA-DOG/go-sqlmock/connection.go:25 +0x2d0
      database/sql.(*driverConn).finalClose()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:310 +0x175
      database/sql.finalCloser.(database/sql.finalClose)·fm()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:398 +0x57
      database/sql.(*DB).Close()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:487 +0x6fa
      github.com/jnwhiteh/migration.TestFailingToGetCurrentVersion()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:54 +0x331
      testing.tRunner()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:422 +0x10f
    
    Goroutine 10 (running) created at:
      testing.RunTests()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:504 +0xb46
      testing.Main()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:435 +0xa2
      main.main()
          github.com/jnwhiteh/migration/_test/_testmain.go:61 +0xdc
    
    Goroutine 8 (finished) created at:
      testing.RunTests()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:504 +0xb46
      testing.Main()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:435 +0xa2
      main.main()
          github.com/jnwhiteh/migration/_test/_testmain.go:61 +0xdc
    ==================
    PASS
    Found 2 data race(s)
    exit status 66
    FAIL	github.com/jnwhiteh/migration	1.105s

**Comment by l3pp4rd** [comment]
thanks @jnwhiteh and @wongak for the discussion and your branch to support concurrency. The **refactor** branch is now covering all the issues which the library had in initial version. It will be merged as soon as the README and examples are updated, cheers

**Comment by jnwhiteh** [comment]
Thanks for the update!
