### ISSUE TITLE
Expectations not met for  a sql function uuid() in insert.

### ISSUE THREAD

**Issue by slokesh184** [DATA-DOG/go-sqlmock#90]
Sorry for opening this as an issue.

Query = `INSERT INTO Provider (provider_id, provider_name, url, provider_type, display_name, sync_time)
				        VALUES (uuid(), :provider_name, :url, :provider_type, :display_name, :sync_time)`
I would like to do mock.ExpectExec like below. 
mock.ExpectExec("(INSERT INTO CloudProvider \\(provider_id, provider_name, url, provider_type, display_name, sync_time\\)"+
		" VALUES \\(\\?,\\?, \\?, \\?, \\?, \\?\\))").WithArgs(
               "1234-1234",
		"Mock",
		"http://localhost:5000",
		"DOCKER_REGISTRY",
		"Docker_Registry_Mock",
		30).WillReturnResult(sqlmock.NewResult(1234, 1))
Which throws mismatch error. How to use sql functions in mock.Expectexec. 

I have tried uuid.NewV4().string() etc nothing seems to work can someone help me out with this.

**Comment by l3pp4rd** [comment]
please format properly your code and questions, if you ask for someones time, at least respect them enough and properly write your question.
