### ISSUE TITLE
Can mock instances be reused?

### ISSUE THREAD

**Issue by briansan** [DATA-DOG/go-sqlmock#91]
Could I declare `db` and `mock` in global `var`, set in `init` and reuse through testing suite? I will just try and learn, but it would be nice to have such information in the docs.

i.e.
```
var (
  db *sql.DB
  mock *sqlmock.Sqlmock
)

func init() {
  db, mock, _ = sqlmock.New() 
}

func Test1() {
  // use db and mock for one set of tests
}

func Test2() {
  // use db and mock for another set of tests
}

**Comment by l3pp4rd** [comment]
it would be not a good idea if you would try to do this.

why?
- no concurrency safety, `go test -race` would simply fail and that is a very important point.
- it would always append list of expectations to be asserted in the same slice, which may be an issue if you have lots of tests.

I understand that it has some boilerplate code, but that is the way forward, you may have a helper method like:

``` go
func withinSqlMock(t *testing.T, fn func(*sql.DB, sqlmock.Sqlmock)) {
	t.Parallel()
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
	}
	defer db.Close()

	fn(db, mock)

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Fatalf("there were unfulfilled expections: %s", err)
	}
}
```

and it accepts a func which actually tests all the behavior.

``` go
func MyTestMethod(t *testing.T) {
	withinSqlMock(t, func(db *sql.DB, mock sqlmock.Sqlmock) {
		mock.ExpectQuery("some sql query which will not be called").WillReturnRows(sqlmock.NewRows([]string{"id"}))
	})
}
```

**Comment by briansan** [comment]
this is an awesome solution, thank you!

**Comment by briansan** [comment]
is it worth to keep this open to add this to document?

**Comment by l3pp4rd** [comment]
well, I think this is straight forward, but maybe can be put somewhere in readme in case if it is hard to figure out

**Comment by l3pp4rd** [comment]
well, users will be able to look it up here, don't want to enforce certain practices

**Comment by ed-randall-blk** [comment]
Rather than the above roll-your-own approach, we prefer to use it in conjunction with stretchr/testify suite and arrange to have the db + sqlmock initialised in suite `SetupSubTest()` and the expectations check in `TearDownSubTest()` methods.

What we havn't yet solved is a way to be *sure* that `mock.ExpectationsWereMet()` is always called, ie. developer hasn't mis-spelled `TearDownSubTest` or used `AfterTest` or `AfterSuite` by mistake.
