### ISSUE TITLE
Issue on multiple mocks and table driven tests

### ISSUE THREAD

**Issue by madshov** [DATA-DOG/go-sqlmock#94]
Hi,

I'm getting an `there is a remaining expectation which was not matched` when running a table driven test with two test cases.

Basically I'm trying to test for an invalid product id in the product table and an invalid EAN in the EAN table.
So I have two sets of mocks like in the below:
   ```
 // Mock selects for test struct 1.
 // Invalid product for product id.
    mock.ExpectQuery("^SELECT (.+) FROM product p WHERE product_id = (.+)$").
        WithArgs("product.id").
        WillReturnRows(sqlmock.NewRows([]string{"product_id", "image", "price", "title"}))
        
    // Mock selects for test 2.
    // Invalid ean for product id
    mock.ExpectQuery("^SELECT (.+) FROM product p WHERE product_id = (.+)$").
        WithArgs("product.id").
        WillReturnRows(sqlmock.NewRows([]string{"product_id", "image", "price", "title"}).  
        AddRow("product.id","ean","image","price","title"))
    mock.ExpectQuery("^SELECT (.+) FROM ean e WHERE ean = (.+)$").
        WithArgs("ean").
        WillReturnRows(sqlmock.NewRows([]string{"ean", "reference"}))
```
When I assert ExpectationsWereMet, I get the error, that seems to be from the second product select:
```
Received unexpected error:
       there is a remaining expectation which was not matched: ExpectedQuery => expecting Query, QueryContext or QueryRow which:
	 - matches sql: '^SELECT (.+) FROM product p WHERE product_id = (.+)$'
	- is with arguments:
	0 - product.id
	- should return rows:
	row 0 - [product.id ean image price title]
```
 I have been through the code, dumped input and output for that particular function. Everything seems to match with the remaining unmatched expectation. This only happens when I do multiple tests, not if I run each test individually. I'm unsure if this is a bug, or I'm mocking the SQL statements incorrectly for a table driven test. Have anyone any suggestions or advice?
Thanks for an otherwise great test tool.

**Comment by l3pp4rd** [comment]
Hi, is your data table a **map**? if so it may not execute in exact sequence as you create it, go iterates it randomly, see golang manual for maps (advice create data tables as slices, or set Sqlmock option for unordered matching). Otherwise show me all the code necessary to run a test.

If you have remaining expectations, then it means it was never matched or executed. see your code first. I'm 99% sure there is a mistake in your code, the library is widely used

**Comment by madshov** [comment]
My data table is a slice of structs:
Something like:
    ```
var tests = []struct {
        have []lib.Product
        want []ean
        err  error
    }
```
I'll try to debug a bit further. Thanks

**Comment by madshov** [comment]
Hi,
I realized that my problem was with my code. You can close this. Sorry for the inconvenience.
Thanks again.
