### ISSUE TITLE
ExpectedPrepare.WillReturnError working ?

### ISSUE THREAD

**Issue by barasher** [DATA-DOG/go-sqlmock#96]
Hi,

First of all, thanks for this db mocking library, it is really very useful for me !

But I have some problem with the WillReturnError of the ExpectedPrepare type.
I'd like to test the way I handle error when preparing an SQL statement.

Let's have an example : 

```go
func TestPrepareWillReturnError(t *testing.T) {
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("error '%s' when initializing the mock, err)
	}
	defer db.Close()
	mock.ExpectPrepare("insert into t").WillReturnError(fmt.Errorf("an error"))

	ps, err2 := db.Prepare("insert into t values (?)")
	defer ps.Close()

	assert.NotNil(t, err2, "should not have raised an error")
}
```

Here is the "panic" that I get when executing the test :  

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]

	panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x521d48]

goroutine 19 [running]:
testing.tRunner.func1(0xc42011e0f0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x6a2d00, 0x873bb0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
database/sql.(*Stmt).Close(0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:2335 +0x38
github.com/X/Y/controler.TestPrepareWillReturnError(0xc42011e0f0)
	/home/barasher/go/src/github.com/X/Y/controler/controler_test.go:90 +0x271
testing.tRunner(0xc42011e0f0, 0x70b4b0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

Process finished with exit code 2
```

That's my first personnal project using Go, so I'm pretty sure that I'm doing things wrong ; I just want to be sure :p

Anyway, thanks a lot !

**Comment by l3pp4rd** [comment]
Hi, thanks, this one is interesting, the error comes from go sql package, mutex is not initialized.

``` go
func (s *Stmt) Close() error {
	s.closemu.Lock()
```

maybe there were some changes in the sql library, which requires to adapt the driver. I will investigate this when I have more time, thanks for reporting.

**Comment by l3pp4rd** [comment]
Well, haven't noticed that prepare returns error. Do you know that you always should first check an error in golang as a standard practice.

So what happens is:

1. `ps, err2 := db.Prepare("insert into t values (?)")` returns `ps == nil` and `err != nil`.
2. you defer `ps.Close` in the end which is `nil` and that is where the panic comes from.

If you would not specify to return an error, you would get a prepared statement otherwise

**Comment by barasher** [comment]
I feel so stupid...
Even if I'm discovering GO, I knew it !
Sorry !

**Comment by l3pp4rd** [comment]
it is fine, just be more careful when submitting issue
